### ISSUE TITLE
Code to simulate photometry for senstivity tests

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#106]
Need to be able to perform sensitivity tests given a set of filters.  How well do we recover BEAST parameters given simulated data.  This was done for the HST filters by @heddyarab , but the code is not in the BEAST repository.  Motivation is to be able to ask what WFIRST or JWST filters should be proposed for to get the best recovery of BEAST parameters.

**Comment by karllark** [comment]
@lcjohnso : you have code for this or at least part of this right?  Interest in this from @cemurray3 for a HST proposal.

**Comment by karllark** [comment]
Working on this during BEAST HackDay 13 Sept.
I will work on generating the simulated observations from a BEAST grid including documentation.
@cmurray-astro & @petiay : code/docs to run the simulated data through the BEAST fitting and making the input-output sensitivity plots and generically plotting CMDs (from real or simulated data).

**Comment by petiay** [comment]
Hi Karl,

While I remember how to do a pull request properly (need to make sure I have the current BEAST version first, then I’ll write a doc string too), I am attaching the sample generic CMD plotting code I wrote.  Let me know if the section starting on line 53, “Convert from flux to mags”, makes sense for now.

I had fun today, even if this was a very limited contribution.  Good job on keeping the BEAST going and all the development efforts so far.  I’ll keep participating and I’ll keep you posted on how the BEAST is coming in handy with the SMIDGE data.

Petia


On Sep 13, 2018, at 7:48 AM, Karl Gordon <notifications@github.com<mailto:notifications@github.com>> wrote:


Working on this during BEAST HackDay 13 Sept.
I will work on generating the simulated observations from a BEAST grid including documentation.
@cmurray-astro<https://github.com/cmurray-astro> & @petiay<https://github.com/petiay> : code/docs to run the simulated data through the BEAST fitting and making the input-output sensitivity plots and generically plotting CMDs (from real or simulated data).

**Comment by karllark** [comment]
@petiay : I did not get any attachment either in email or here.  Would love to try out your plotting code!  :-)
It was great to see and talk with you today.  Looking forward to the next BEAST HackDay.  I hope we can keep some of the momentum going via email, slack, and github!

**Comment by petiay** [comment]
Hi Karl,

Maybe attachments are disabled through the github email (?), so I am sending this also to your STScI address.
Same here - I plan to contribute as much as I can and keep this going until the next Hack day!

Petia



On Sep 14, 2018, at 7:37 AM, Karl Gordon <notifications@github.com<mailto:notifications@github.com>> wrote:


@petiay<https://github.com/petiay> : I did not get any attachment either in email or here. Would love to try out your plotting code! :-)
It was great to see and talk with you today. Looking forward to the next BEAST HackDay. I hope we can keep some of the momentum going via email, slack, and github!

**Comment by karllark** [comment]
Yes, the conversion from flux to mags looks correct to me.  The fluxes it the 'rate' column of the observed catalogs (and simulated catalogs) is in "normalized Vega fluxes."  So, basically flux/vega_flux.  Hence converting to magnitudes is straightforward.

Are you planning submitting this code as a PR?  You definitely should.

**Comment by petiay** [comment]
Finally - PR submitted.

**Comment by karllark** [comment]
This has been done by multiple PRs.  Closing.
