### ISSUE TITLE
Documentation: report experience

### ISSUE THREAD

**Issue by mfouesneau** [BEAST-Fitting/beast#112]
It would be good to have a page/section in the documentation that shares our experience with BEAST and in particular the results and interpretation.

Basically, we'd like to have something that helps people avoiding writing papers with absolute mis-understanding. 

For example, why changing mass function or metallicity distribution ends up changing significantly the analysis for some set of stars (maybe the ones of interests)...

**Comment by karllark** [comment]
This is a great idea.  Would be especially useful if we can quantify the effect of changing the priors.  I can imagine this would be useful not only for others, but also us - slides for talks, general understanding, discussions with others, ...

**Comment by mfouesneau** [comment]
We could also include figures that we/one can use in talks that give how BEAST works.

**Comment by karllark** [comment]
Closing as there is now a place in the documentation for such experiences so full fulling the point of this issue.  Further additions should be added as separate issues.
