### ISSUE TITLE
"extra_filters" script seems to be missing

### ISSUE THREAD

**Issue by meredith-durbin** [BEAST-Fitting/beast#115]
In `beast/examples/phat_small/run_beast.py`, there is the following commented line:

`from extra_filters import make_integration_filter, make_top_hat_filter`

I can't find anything named `extra_filters` anywhere (including in `old`), and the `make_integration_filter` and `make_top_hat_filter` functions haven't been moved elsewhere or reimplemented under other names as far as I can tell. I'm working from branch py3_compat and have also checked master.

It'd be good to have this or similar functionality reinstated for working with filters that aren't in the database. (Or, if I've just missed where `extra_filters` lives, I can update the commented line.)

**Comment by galaxyumi** [comment]
Karl, did you remove it or move it to a more proper directory? 
That is a necessary code to get UV flux or photon flux within a user defined wavelength range.

**Comment by karllark** [comment]
Yumi, I never put it in the example directory.  It should be added to the tools directory.  I can do this or you can.  :-)
