### ISSUE TITLE
New Path to Padova output files

### ISSUE THREAD

**Issue by benw1** [BEAST-Fitting/beast#122]
They moved the Padova web server and changed the default tmp directory.  Now the recovered files do not need the ~lgirardi in the URL.  Leo put in a symlink to address it for now, but really the code should be updated with the ~lgirardi/ removed from the scripts.

**Comment by mfouesneau** [comment]
Can you be more clear?
The code uses `http://stev.oapd.inaf.it/cgi-bin/cmd` and reads the output data url from the website.

**Comment by karllark** [comment]
See the pull request #123 for the solution.  Lea found this issue and was already thinking of fixing it when this issue was created.  Yeah for more BEAST developers!

**Comment by karllark** [comment]
Fixed by pull request #123.
