### ISSUE TITLE
Remove Merged Branches

### ISSUE THREAD

**Issue by lcjohnso** [BEAST-Fitting/beast#125]
It is difficult to track on-going development (especially concerning documentation) due to the large number of branches that have previously been merged but not removed from the codebase.

Here is a list of branches that appear ready for pruning:
py3_compat merged by https://github.com/BEAST-Fitting/beast/pull/113
adjust_dust_prior by https://github.com/BEAST-Fitting/beast/pull/104
doc_update by https://github.com/BEAST-Fitting/beast/pull/99
travis_ci_setup by https://github.com/BEAST-Fitting/beast/pull/96
readthedocs_fixes by https://github.com/BEAST-Fitting/beast/pull/92, https://github.com/BEAST-Fitting/beast/pull/91, https://github.com/BEAST-Fitting/beast/pull/90, https://github.com/BEAST-Fitting/beast/pull/89, https://github.com/BEAST-Fitting/beast/pull/88
doc_fileformats by https://github.com/BEAST-Fitting/beast/pull/87
dtu_plots by https://github.com/BEAST-Fitting/beast/pull/86

**Comment by karllark** [comment]
This is a good point.  I've been on the fence on if I should prune or not.  This pushes me over.  They always can be recovered of course.

**Comment by karllark** [comment]
Done.  Very useful as the list of branches now only shows active ones.  And I can see I have two more active branches than I thought.  Good reminder to do something with those branches.
