### ISSUE TITLE
Cleanup documenation

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#131]
Need to cleanup the documentation.  See:
http://documentation-style-guide-sphinx.readthedocs.io/en/latest/style-guide.html

Would also be good to "brand" the documentation by changing from the default astropy-template docs titles to something more BEAST related.  Should be "easy."  Hah.

Could also add in the generic info on contributing to such a open source project in the base README.rst. 
See: https://github.com/karllark/dust_extinction

Also, maybe add in a link from the base README.rst to the beast subdirectory README.rst that gives the organization of the beast files.

**Comment by cemurray3** [comment]
Submitted pull request to add information about contributing based on README in dust_extinction
