### ISSUE TITLE
Add example of XSEDE run

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#14]
Need to add the code required to run on large computers (e.g., XSEDE computers).
Useful for how to run parallel fits with the BEAST efficiently.

**Comment by lea-hagen** [comment]
I just stumbled across this issue.  What exactly needs to be added?  I've added/updated some code to work with slurm (#401), but perhaps there's more that would be useful.

**Comment by karllark** [comment]
Probably what is needed is docs on how to get the files that will work with slurm.
