### ISSUE TITLE
Library file location for installed version of the BEAST

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#141]
The BEAST can be installed.  When this is done, the location of the library files is incorrect.  Need to find a solution for this case.  Maybe in /tmp and downloaded as needed (like the travis testing).  Or maybe in a default location in the user's home directory (e.g., '.beast' subdirectory).   Or maybe in a user specified location via a system environment variable.

**Comment by mfouesneau** [comment]
Can you be more explicit?

in `beast.config` there must be a `libdir` variable that points to the library.
libsdir = __ROOT__ + '/libs/'

**Comment by karllark** [comment]
The issue here is that if a user installs the BEAST via pip (when this capability is added), the library location does not make sense in the current method.  Thus, we need a different way of specifying where the library files are and (possibly) downloading them automatically.

**Comment by karllark** [comment]
This issue subsumed by issue #155.
