### ISSUE TITLE
Do we still tag models that are fainter than the faintest ASTs with negative errors?

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#154]
https://github.com/BEAST-Fitting/beast/blob/adedfb70dbfa2e0d99cd7562360541f6e9f02322/beast/fitting/trim_grid.py#L93

**Comment by galaxyumi** [comment]
@karllark, could you also review the for loop between line 120-132 in trim_grid. py? This part currently selects all models with fluxes 3 sigma upper and below in the last band (i.e., F160W for PHAT) in a given n_filters. Don't we want to apply the same n_detected cut for trimming the model grid as well?

**Comment by karllark** [comment]
The lines 120-132 give the for loop over all the bands (not just the last one).  The indexes used are updated as each band is tested, so that the final indexes has the condition for all the bands.  The update of the indexes is done on lines 131-132.  This check is done for every band as if one band is not fit well, the prob is going to be low.

**Comment by karllark** [comment]
Yes, we still tag the models that are fainter than the faintest ASTs.  This is on lines 110-118 of generic_noisemodel.py for the toothpick model.  
A similar set of code would be needed for the trunchen noisemodel.  I have not implemented a generic noisemodel for the trunchen case.  Probably need to do better with naming.  :-)

**Comment by karllark** [comment]
@galaxyumi : does this answer your questions?

**Comment by galaxyumi** [comment]
Thanks, Karl! I now see how you updated indexes for each band. That is clear to me now.

**Comment by karllark** [comment]
Ok.  I will close this issue then.

**Comment by galaxyumi** [comment]
Okay, I was looking at the trunchen noisemodel.  How did we do for the trunchen model before?

**Comment by karllark** [comment]
We did something similar.  The code for the trunchen was in the phat_production example (now removed, but still in the commit history).  I do need to dig this out and make an example for using the trunchen model.  Is this this something you need?  If so, we should move this discussion to #66.

**Comment by galaxyumi** [comment]
No need for now. I just wanted to make sure our codes are running in the ways our comments say.
