### ISSUE TITLE
Docs: stellar atmosphere grids - when/how to use

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#158]
There are multiple stellar atmosphere grids that can be used in the BEAST.  The "standard" is Tlusty + Kurucz.  More are being introduced, but no documentation is given on how or when to use alternative grids.  Do they replace the "standard"?  Enhance?

**Comment by meredith-durbin** [comment]
I would be happy to add some documentation on how to use non-default grids, since I just went through the process of figuring that out a few weeks ago.

**Comment by karllark** [comment]
That would be great!

**Comment by lcjohnso** [comment]
I'm working on this now and will assemble a PR soon.
