### ISSUE TITLE
Stellar library files for user download

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#176]
Need to get the new ones so that they can be added to the BEAST library download.

**Comment by karllark** [comment]
Some libraries are defined in stelllib.py that are not available in the library download file.

**Comment by karllark** [comment]
Code from stelllib.py.

    'basel_2.2_pegase': __ROOT__ + '/libs/BaSeL_v2.2.pegase.grid.fits',
    'elodie_3.1': __ROOT__ + '/libs/Elodie_v3.1.grid.fits',
    'kurucz': __ROOT__ + '/libs/kurucz2004.grid.fits',
    'tlusty': __ROOT__ + '/libs/tlusty.lowres.grid.fits',
    'btsettl': __ROOT__ + '/libs/bt-settl.lowres.grid.fits',
    'btsettl_medres': __ROOT__ + '/libs/bt-settl.medres.grid.fits',
    'munari': __ROOT__ + '/libs/atlas9-munari.hires.grid.fits'

We have kurucz and tlusty.
@mfouesneau : can you provide the basel and elodie files?
@lcjohnso : can you provide the btsettl (both versions) and munari?

**Comment by karllark** [comment]
We should strive to not have stellar libraries defined in stelllib.py that we do not provide for download.

**Comment by mfouesneau** [comment]
files are here: https://github.com/mfouesneau/pystellibs/tree/master/pystellibs/libs

**Comment by karllark** [comment]
@mfouesneau : Thanks for the link.  That provides btsettl (lowres), basel, and munari.  
What about elodie?  Or is this old and I should remove from stelllib.py?
I also see a file for rauch - what models are these?

**Comment by mfouesneau** [comment]
Elodie is quite substantial. That's why I do not put it on Github. I'll try to put it on an ftp. BTW Rauch could be useful if you plan to do White Dwarfs.

**Comment by lcjohnso** [comment]
Library files for BT-Settl and Munari are currently available here:
https://cass.ucsd.edu/~lcj/beast/

**Comment by karllark** [comment]
The reasonable sized files are in and are downloaded with the rest of the libraries.  Closing this issue.
