### ISSUE TITLE
Bug: Appending to HDF file does not work, PyTables syntax update.

### ISSUE THREAD

**Issue by drvdputt** [BEAST-Fitting/beast#186]
Trying to do a simple append like this:
`  g.writeHDF(spec_fname, append=True)`

throws the following exception

```
Traceback (most recent call last):
  File /beast-wd/beast/physicsmodel/helpers/gridbackends.py", line 335, in writeHDF
    node = hd.getNode('/seds')
  File /beast-wd/beast/physicsmodel/helpers/hdfstore.py", line 472, in __getattr__
    raise AttributeError(msg.format(type(self).__name__, name))
AttributeError: 'HDFStore' object has no attribute 'getNode'
```

This is because of changes in PyTables, migrating to python 3 (https://www.pytables.org/MIGRATING_TO_3.x.html).

Replacing getNode with get_node solves this problem, so maybe we should do a search and replace. I don't know if python 2 compatibility will be preserved though.

**Comment by karllark** [comment]
Are we using the append option?  I'm assuming yes.  If so, then isn't this a show-stopper?

**Comment by drvdputt** [comment]
The append option is set to True in make_spectral_grid and make_extinguished_grid, where it is used to write out the grid in steps instead of all at once, to save memory.

The actual append functionality is only used however when the chunksize argument for one the grid generation functions is used. The only places where a chunksize is actually used, are two tests which have been disabled (with xx added to their name).

I came across this while experimenting with making subgrids, and then merging them. So if anyone tries to do something similar, they will run into this.

**Comment by karllark** [comment]
This is tracked through a bigger issue now.
