### ISSUE TITLE
Standalone run script with absolute datamodel import, avoid other datamodel imports

### ISSUE THREAD

**Issue by drvdputt** [BEAST-Fitting/beast#187]
It is possible to import a python file as a module directly from a file path, although the exact way of doing it is different between python versions.
https://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path

By importing datamodel from the working directory this way, we would be able to generalize the run script, put it in a scripts directory, and install it for the pip version. Users then no longer need to copy the `phat_small/run_beast` example. Having to put a beast symlink might also be avoided this way, as the run script will be in a more convenient location, with direct access to the beast module.

Note that there are still some other places (e.g. `make_ast_xy_list`) the code where datamodel is imported, usually out of convenience. This usually happens out of convenience, for passing a bunch of filenames for example. We should get rid of these imports, and pass whatever was used as function parameters instead.

**Comment by karllark** [comment]
Now being tracked in issue #320.  This will be more general and give the same capabilities.
