### ISSUE TITLE
Production run physics model grid definition

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#194]
What is the grid min/max and spacing needed for production?
What about distances?
Use reported production grid from BEAST paper?

**Comment by karllark** [comment]
Looks good to me.  Matches the BEAST paper for the PHAT example run section.

**Comment by lea-hagen** [comment]
I did another METAL field with the following metallicities:
```z = [0.0015, 0.0076, 0.015]```
which correspond to a tenth solar, half solar, and solar.  The LMC is typically half-solar, but since there is a spread of metallicities, I opted to include higher/lower ones as well.

**Comment by karllark** [comment]
Note that the LMC is half solar for present day star formation and ISM.  Older, lower mass stars can have any metallicity below 1/2 solar.
