### ISSUE TITLE
Splitting of ASTs/observations by source density

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#20]
The uncertainties due to crowding/confusion as derived from the ASTs can be strongly dependent on source density.  
Need to add the scripts to split up the ASTs into different source density files.
Same for the observations.

**Comment by karllark** [comment]
@heddyarab Is this something you could do?  You have the code that does this.  At a minimum, it would be good if you could commit the code you currently have.

**Comment by heddyarab** [comment]
Sure. But I cannot find how I can self assign this issue.

**Comment by karllark** [comment]
@heddyarab Does just clicking on the "Assignees" above not work?  In fact, I see the line below the "Assignees" is "No one -- assign yourself" and if I click "assign yourself" it assigns me.  Does this not work for you?

**Comment by heddyarab** [comment]
Nope, I cannot click on "assignees". I remember seeing what you describe few weeks ago but the assign yourself button has disappeared.

**Comment by karllark** [comment]
You need to accept the invitation to become a member of the BEAST group.  Your membership is still pending.

**Comment by karllark** [comment]
This work is being done as part of #114 that address a broader topic.  Closing this issue as it is a duplicate.
