### ISSUE TITLE
Some issues with get_libfile script

### ISSUE THREAD

**Issue by drvdputt** [BEAST-Fitting/beast#204]
The new documentation states that the lib files can be downloaded with
`$ beast/tools/get_libfiles.py`

Some remarks about this:
- It looks like the script is actually called ``get_libfile.py``
- `beast` module is not found
   - a symlink would be needed at the location of the script
   - Alternative solution: run it as `python -m beast.tools.get_libfile` (from the repo root)
- If BEAST_LIBS is not specified, the user needs to do `mkdir beast/libs` first (or you could make the script to this), otherwise it the script will fail.

**Comment by karllark** [comment]
Good point about the name of the file.  Need to fix that.
Did you check if the beast code was installed with pip if the tool would then work?

**Comment by drvdputt** [comment]
Ah yes, if beast is pip installed, then `beast` is found in the site packages.

That then loads the pip version of `config`. If someone wants to use their dev version of `config`, they will have to put `beast` in the PYTHONPATH. So I guess this could be clarified in the docs, along with the spelling error.
