### ISSUE TITLE
PDF1D error

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#223]
New error seen when running phat_small.  Debugging needed.

/home/kgordon/Python_git/beast/beast/fitting/pdf1d.py:57: RuntimeWarning: invalid value encountered in double_scalars
  self.bin_delta = (self.max_val - self.min_val)/(self.nbins-1)

**Comment by drvdputt** [comment]
I just noticed this issue. I'm pretty sure that this is because of the distance implementation. The phat_small example uses only 1 distance bin, so naturally the bin_delta is NaN.

**Comment by karllark** [comment]
Would there be an easy fix?  E.g., just making a default bin_delta when nbins = 1?  Or will this screw up something?

**Comment by drvdputt** [comment]
I tried this, and putting bin_delta to 1 if nbins = 1 works, but there is one test that fails: the distance_p16 column is equal to 783429.642766 (the given distance) instead of 0. So the reference data for this test would need to change.
