### ISSUE TITLE
keeping ASTs within image boundary

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#234]
As @drvdputt noted in #214, there is code to prevent ASTs from having negative x/y coordinates, but nothing to stop the coordinates from being too large.  My initial idea was to use the header of the reference image to define the boundaries, but for the PHAT half-bricks, the image is large enough that it would be optimal to read in just the header, and not the entire fits file.  However, if the header is saved independently of the image with `astropy`, the original image dimensions are not maintained in the header.  @benw1 proposed in an email that we use the photometry catalog to set the maximum x/y, which seems like a good idea to me.

**Comment by karllark** [comment]
It should be straightforward to just read in the header, no?  Maybe using the memmap  keyword?

http://docs.astropy.org/en/stable/io/fits/

**Comment by lea-hagen** [comment]
Yes, reading in the header is fine.  To be more clear, the issue is that when the header is being written into its own file, the `NAXIS*` keywords are automatically generated by astropy.  So when there's no data array, those keywords don't exist.  As far as I can tell, there's no generic way to keep that information.

However, I think this is going to be a moot point.  There is already code [here](https://github.com/BEAST-Fitting/beast/blob/master/beast/observationmodel/ast/make_ast_xy_list.py#L235) that checks the x/y values.  I haven't yet tracked down why there are still ASTs generated outside that range.

**Comment by lea-hagen** [comment]
I believe I have located the problem: it's an issue with `pick_positions_from_map` in `make_ast_xy_list.py`.  The x/y positions from `pick_positions` are fine, but when the source density map (or background map) is used in `pick_positions_from_map`, the RA/Dec are used to define the min/max coordinates (see [here](https://github.com/BEAST-Fitting/beast/blob/master/beast/observationmodel/ast/make_ast_xy_list.py#L112)).  Unless the image is perfectly oriented north-south, the source density maps are guaranteed to have some pixels that extend beyond the edges of the image, since the pixels are evenly spaced in RA/Dec and not in x/y.

I see two possible options:
1. Change the source density and background maps to have pixels oriented along the input x/y.  If the input catalog only has RA/Dec, this would require the input image/header for WCS info.  Or perhaps make the x/y orientation optional, and check in the AST code what the orientation is?  That's sounding pretty complicated.
2. Add the catalog as an input to `pick_positions_from_map` (it's already an input to `pick_positions`).  If the x/y info exists, use the min/max values as an additional constraint.

I'm going to opt for the second option.

**Comment by lea-hagen** [comment]
Here's an image showing the problem.  (the internet connection isn't great here, so I can't show actual images, but hopefully this will work ok)
<img width="559" alt="screenshot" src="https://user-images.githubusercontent.com/32465297/42992782-d7263480-8c09-11e8-8fd3-a4489fedf70f.jpeg">

The background image is the source density map, and the green frame is the approximate image boundary.  The method currently used in `pick_positions_from_map` is to chose one of the pixels from the source density map and randomly pick an RA/Dec (later converted to x/y) within that pixel.  The pixels along the boundary have a decent chance of having an x/y that's not in the image.  Assuming the image is a rectangle, simply checking the chosen x/y against the minimum/maximum will be enough to discard points outside of the image FOV.  If the image isn't rectangular, this won't work perfectly (and neither will the current code), but are there any use cases like that yet?

**Comment by meredith-durbin** [comment]
One way to use the photometry catalog and make almost no assumptions about the shape of the input image would be to use [`scipy.spatial.ConvexHull`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.ConvexHull.html#scipy.spatial.ConvexHull) in conjunction with a Matplotlib Path to define the XY boundaries:

```
import numpy as np
from astropy.table import Table
from matplotlib.path import Path
from scipy.spatial import ConvexHull

t = Table.read('catalog.fits')
coords = np.array([t['X'],t['Y']]).T # there's a weird astropy datatype issue that requires numpy coercion
hull = ConvexHull(coords)
bounds_x, bounds_y = coords[hull.vertices,0], coords[hull.vertices,1]
path = Path(np.array([bounds_x, bounds_y]).T)

# returns boolean array of whether AST coords are within phot catalog boundaries
within_bounds = path.contains_points(ast_xy) # N,2 array of AST X and Y positions
```

It's pretty fast and gets rid of any complications re: image orientation. The only potential failure mode I can think of for this is when there are substantial gaps within the image itself (chip gaps, a sparse field with a large empty region near the edge, etc), but that would be a problem using only the x/y min/max too.

**Comment by meredith-durbin** [comment]
Hm, the X and Y from my half-brick M33 runs are still oriented along a diagonal with empty bits around the edges:
<img width="426" alt="image" src="https://user-images.githubusercontent.com/6032853/42997936-fc77027a-8c07-11e8-8c99-68522f517ec2.png">
This plot is for data with opt+IR photometry, so basically the IR footprint. DOLPHOT uses the drizzled F475W as a reference image, and drizzle defaults to whatever way the F475W observations are oriented, which in this case is ~45° off from WFC3.

In any case, let me know if it works!

**Comment by lea-hagen** [comment]
That would certainly be an option too.  I think the procedure Meredith suggested will still be important for the generic case where a box isn't a good approximation for the boundary.  I have it coded up and am currently testing it on the 17W brick (it's taking 30-40 minutes to read in everything to run, so I've been doing other things while it thinks).  For the PHAT bricks, are there any complications I'm not aware of that would make this procedure non-optimal?  Or do we need to add the RA/Dec corners too?
