### ISSUE TITLE
some questions about production mode

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#237]
I've been re-working the [METAL production mode example](https://github.com/BEAST-Fitting/beast/blob/master/beast/examples/metal_production/run_beast_production.py) a bit, and I have some questions, particularly regarding sub-files.

1. In order to create sub-files, one needs to run `create_source_density_map` and `subdivide_obscat_by_source_density`.  These commands could be added to the example code, but that may require additional inputs (e.g., the filter and magnitude range to use) in `datamodel.py`.

2. The production code has sections for trimming and fitting that are similar to those for shorter runs, but the "Standard Workflow" documentation says to use `setup_batch_beast_trim.py` and `setup_batch_beast_fit.py`.  Is there any objection to replacing those sections with the batch setup codes?  They could be accompanied by loud statements saying to go run the batch code before proceeding.

3. The production code currently takes the source density and sub-source density bins as inputs.  Those inputs are used to construct file names, but assuming one uses the batch setup options, those files are never referenced - the batch setup codes automatically extract the information to create their job files.  Am I missing any other places these might be used, or can I remove these as inputs?

4. A possible exception to the above is generating the AST input list.  However, the AST code has its own option to use the source density map to duplicate sources across source density bins, so it's not clear to me that it should use anything other than the original photometry file.

**Comment by lea-hagen** [comment]
I figured out answers to 2 and 3... the batch fitting does call the fitting routine in `run_beast_production` (along with the subfile information), but the batch trimming currently calls a separate script.

For 1, I'll put those in an example wrapper, so more things don't need to be added to `datamodel`, particularly since they're only relevant to production runs.

**Comment by karllark** [comment]
Are there still questions outstanding?  Or will this issue been closed with pull request #239?

**Comment by lea-hagen** [comment]
I'm still not sure about the ASTs - is it better to do one file that includes many source density bins, or multiple files that each represent a different source density?

But I don't think this issue needs to stay open to address that question.

**Comment by karllark** [comment]
Do you mean for generating the inputs for the ASTs or using the outputs?

**Comment by lea-hagen** [comment]
Generating the inputs.

**Comment by karllark** [comment]
Maybe Ben would know what the most efficient way would be for the AST inputs.  @benw1?  I feel like it would be one file, but maybe that depends on the number of input sources the file?

**Comment by benw1** [comment]
This only matters for parallel processing.  For large image stacks, one really does not want more than a few thousand stars per file, but for small stacks you may want just one file. Best may be a default of 1 file, with a flag one can set for division into x files. It doesn't matter which stars go in which file.

**Comment by lea-hagen** [comment]
Ok.  That's what I currently have implemented in the AST code updates I've been doing.
