### ISSUE TITLE
Add support for other stellar atmosphere models

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#26]
Currently the BEAST is using Kurucz model for LTE and TLUSTY model for non-LTE.

**Comment by lcjohnso** [comment]
Update: work to include BT-Settl is underway.

Adding Aringer will be more difficult, requiring that additional data columns are harvested from the stellar models (e.g., C/O ratio, others?) to match appropriate atmospheres to each grid point.

**Comment by lcjohnso** [comment]
BT-Settl and Munari libraries have been added via PR https://github.com/BEAST-Fitting/beast/pull/126.

Still ToDo: Aringer for PARSEC+COLIBRI, and added documentation about differences between various speclib choices.

**Comment by galaxyumi** [comment]
It would be great if we add the WM basic model for hot stars.

**Comment by karllark** [comment]
@galaxyumi : can you provide references and locations for an appropriate grid of spectra for WM basic?  Also, can you provide a bit more info?  Like, would this be a drop in replacement for the TLusty models?  I am not all that familiar with the WM basic models.

**Comment by galaxyumi** [comment]
Reference for the WM-basic is Pauldrach+98 and Pauldrach+01. Here is the link we can download their original spectra: http://www.usm.uni-muenchen.de/people/adi/Programs/Programs.html. And the Cloudy provide rebinned spectral grid as well (http://www.nublado.org/wiki/StellarAtmospheres). I do not know the very details about the WM-basic. But the main difference between the TLUSTY and WM-basic is the geometry. While the TLUSTY solve the non-LTE solution for the plane-parallel geometry, the WM-basic includes a spherically expanding stellar wind. I don't know about other science cases, but if ones about O/B stars, it would be good to have an option to pick the WM-basic for the non-LTE grid.

**Comment by karllark** [comment]
A brief look at the grid for WM-basic indicates that it is not as large as the TLUSTY grid.  
Would be useful to have direct comparisons between the models that overlap between WM-basic and TLUSTY.  Plots of spectra.  Maybe the WM-basic can replace the TLUSTY models where they exist and we can use the TLUSTY models for the rest of the non-LTE cases?
Very limited in abundances too.

**Comment by galaxyumi** [comment]
I like the idea that replacing the TLUSTY models with the WM-basic where they exist for in the non-LTE regime. I have seen many O/B star studies preferring the WM-basic models.

**Comment by karllark** [comment]
@galaxyumi : Is this something that you would like to work on?

**Comment by galaxyumi** [comment]
Sure. I will try to find time to work on this soon.

**Comment by karllark** [comment]
Great!

**Comment by karllark** [comment]
Closing this issue as a few new atmosphere grids have been added.  Adding additional should be done with an issue for each specific grid to be added.  E.g., see #180.
