### ISSUE TITLE
Picking ASTs efficiently

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#268]
Need to pick physicsmodels for ASTs as efficiently as possible.  They are costly.

Ideally, we would pick physicsmodel grid points that are equal distance from  each other in the nD space of the observations/noise parameters.  For PHAT, the nD space is the 6 observed flux bands, the source density, and residual surface brightness.  So 8 dimensions.

**Comment by benw1** [comment]
Let's try interpolating in a few dimensions (across stellar density bins first?).  One test would be to fit a sample using ASTs with many stellar density bins, then refitting only including every other stellar density bin to see if the results are equivalent.  Similar tests could be done for other parameters as well until we figure out where the actual results start changing significantly.

**Comment by karllark** [comment]
New being tracked in #293 and #308.
