### ISSUE TITLE
match pixel definitions for background and source density maps

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#274]
The way maps are gridded for the background maps and source density maps are different:
* [create_background_density_map](https://github.com/BEAST-Fitting/beast/blob/master/beast/tools/create_background_density_map.py): keyword `npix` sets the dimensions of the grid (`npix=10` means a 10x10 grid)
* [create_source_density_map](https://github.com/BEAST-Fitting/beast/blob/master/beast/tools/create_source_density_map.py): keyword `pix_size` sets the size of the pixels in the grid (`pix_size=10` means each pixel is 10"x10")

It would be more convenient to have the definitions be the same so the maps could have the same WCS.  I don't yet know if it's necessary for a fully functioning BEAST run (creating ASTs, modeling, etc), or if changing either of them will break code elsewhere.  Maybe just change both to make them compatible with either pixel definition.

@drvdputt, any thoughts?

**Comment by drvdputt** [comment]
The two types of maps are stored in exactly the same format (hd5 with a specific set of columns).

Also, I don't think the scripts to create them are called from anywhere. Changing the options shouldn't break anything.

But it might be possible to merge the two types into a single create_map script, one that supports both background density and source density using a command line switch. This script could then also support both ways to specify the tile size.

**Comment by lea-hagen** [comment]
Merging them together does sound like a good idea.
