### ISSUE TITLE
running multiple fields with same SED grid

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#283]
For surveys with multiple fields (METAL, PHAT, etc), it is useful to have one file for the SED grid, rather than one [identical] file generated for each of the fields, as the current method does.

In implementing this for the METAL production example, I'm finding that several of the tools (like batch trimming) have the current file `./projectname/projectname_seds.grid.hd5` hard-coded.  Changing that to be more general will require reformatting some of the inputs and intermediate files.

**Comment by lea-hagen** [comment]
Came across a problem: in the case of METAL, different fields have different subsets of the filter set, so one master grid won't work.  I created issue #285 to address it this.

**Comment by karllark** [comment]
Assuming PR #290 addressed this issue.  If not, please reopen.
