### ISSUE TITLE
access subset of filters in SED grid

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#285]
It would be nice to create a single SED grid with some set of filters, and then run the BEAST for a given field that uses a subset of those filters.  Then, for surveys like METAL, you could use the same grid for all of the fields, rather than generating a new one each time.

**Comment by cmurray-astro** [comment]
Working on this today! The plan is to create a script to extract subsets (e.g., filters) from a master physics model grid, to avoid jamming this capability into the BEAST.

**Comment by karllark** [comment]
Hacking a solution to this for proposals.  But it will be a true hack.  Should be done better and setup such that the filters to be fit can be specified and then filtered when the observed catalog, physics grid, and observation (noise model) grid files are read in.  Should be easier to do this once the file formats are revised as part of #299.

**Comment by karllark** [comment]
Done in #302.  Maybe could do this better, but at least there is a solution and it is even documented.
