### ISSUE TITLE
plots of 2D PDFs

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#303]
In `plot_indiv_fit`, there are 1D PDFs for the fitted parameters.  We should also add a plot of 2D PDFs to identify degeneracies between parameter fits.

**Comment by karllark** [comment]
How do we get the data to make these plots?  The 1D pPDFs are saved.   But not the 2D pPDFs between all pairs of parameters.  Can this be determined from the sparse nD pPDFs?

**Comment by karllark** [comment]
I think this could be done from the sparse sampling of the nD pPDFs that we save.  Especially now that we save 500 samples be default.

**Comment by lea-hagen** [comment]
Agreed.  Yet another thing to add to #333!

**Comment by karllark** [comment]
Done in PR #495.
