### ISSUE TITLE
comparison of AST selection methods

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#308]
I'm working on visualizations of ASTs.  To start, using the SMIDGE catalog, here is a comparison between the two methods of selecting ASTs.  Both methods are applied after discarding SEDs that are not observable (there are bands either too bright or too faint to be in the catalog).
* original method: for every age bin (typically 28), randomly select some number of SEDs (default is 70), for a total of 1960 artificial stars
* new method (introduced in #185): randomly select SEDs, and only add an SED if at least one band has less than the specified number (typically 50) in its magnitude bin (typically 25 bins), for which I ended up with 2320 artificial stars

These are the normalized histograms of artificial stars in each bin.  The original method is not selecting many bright SEDs, presumably because they're more rare.  These brighter bins (in particular the brightest F275W bin) were the last to get filled with the new method, since it took quite a few random selections to identify bright enough SEDs.  On the faint end, the new method seems to end up with a bunch of extra stars, maybe because they're chosen to fill up slightly-less-faint bins in other bands.  I'm not quite sure why the original method doesn't pick out faint things, since I'd guess those would be more common.

(also, I haven't figured out how to make the image any smaller)

![compare_ast](https://user-images.githubusercontent.com/32465297/56913597-10b27600-6a80-11e9-9019-b3390cd7f91c.png)

**Comment by karllark** [comment]
Nice visualization.  No sure either why there is a bias against the faint sources.  Is the old way using the density of sources in the observed catalog in picking ASTs from the BEAST grid?

Note that for the completeness calculation (needed for MegaBEAST), we will need ASTs both brighter and fainter than are in the observed catalog.  Need to have completeness measurements for *all* BEAST models to do the ensemble modeling correctly.

**Comment by lea-hagen** [comment]
For the source density: The procedure has typically been to select SEDs, and then replicate them across source density bins (so each SED is done 20 times in each SD bin).  This above numbers are just the initial SEDs without any duplicating.

I hadn't thought about the completeness calculations for the MegaBEAST.  I'm not sure if we can answer this yet, but how many samples would we need for the rest of the grid?  And is a certain number of ASTs per flux bin the proper way to do it, or do we need to ensure even sampling across the physical parameters?

**Comment by lea-hagen** [comment]
To clarify based on conversation, the old method does not have any explicit weighting to choose SEDs in the more dense parts of the CMD.  However, it does work out to match the flux distribution fairly closely.  In the plots below, I've added a histogram for the model grid.

![compare_ast](https://user-images.githubusercontent.com/32465297/56922009-38f89f80-6a95-11e9-9c84-3512358c4e8e.png)

**Comment by karllark** [comment]
@lea-hagen : do you know what the bump at Vega mags of ~50 is from in the model?  This seems odd.  Could you determine what the physical parameters of those models are?  Off topic, but have only seen this on these neat plots.

**Comment by lea-hagen** [comment]
Here is a CMD of all the models (including lots of smearing from the range of A_V values).  The pixel values are log-scaled.
![grid_cmd](https://user-images.githubusercontent.com/32465297/56991306-5006c280-6b65-11e9-875d-ea2beac21e83.png)

These are the 16th, 50th, and 84th percentiles for the models in the blob on the bottom.  I'm not sure what's going on with the luminosity - all of the `mbolmag` values are precisely 29.767, so maybe it's something weird with them being so faint.
```
M_act: 0.553 0.600 0.832
M_ini: 1.028 1.866 3.266
logL: -9.999 -9.999 -9.999
logT: 4.063 4.096 4.467
logg: 1.786 1.950 2.919
logA: 8.400 9.149 9.750
radius: 3.88e-07 2.14e-06 2.49e-06
```
Lastly, I tried running the flux-bin-based AST code (`pick_models_toothpick_style`) using the whole range of magnitudes in the BEAST grid.  After sampling something like 450 million SEDs, it still hadn't found any of the faint ones.  At first glance, the code looks like it's already set up to efficiently find them, so it'll probably just need some minor edits.

**Comment by karllark** [comment]
Very weird.  I feel we should track these down and exclude them from the BEAST grid.  The radii you give are *very* small.  They really do look like they may be white dwarfs.  Maybe we need to filter out anything with logL values of -99.99? 

Maybe create a separate issue for this referencing this issue?

**Comment by lea-hagen** [comment]
Going back to the ASTs part of this issue, I ran it with the whole SED grid flux range (ignoring SEDs with `logL=-9.999`).  These are the same histograms as above, but with an additional dotted line showing the distribution of these new ASTs.  For 40 bins and at least 50 stars per bin, this is 3409 SEDs.
![compare_ast](https://user-images.githubusercontent.com/32465297/57039235-1cda3700-6c2a-11e9-92d5-edaa4c18a979.png)

**Comment by karllark** [comment]
Make the full list (dotted line).  Split the AST input catalog 1-2 mag below the min observed flux in each band (of course the appropriate combo).  Use the bright set.

Only 1 repeat for each AST for each source density bin.

100,000 is a maximum # of ASTs.

**Comment by karllark** [comment]
Closing this issue as the decision has been made.
