### ISSUE TITLE
anomalous faint points in model grid

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#309]
Making a new issue for discussion started in #308.

The one sentence summary: There is a cluster of extremely faint sources in the model grid whose origin is unknown, and we may want to delete them.

**Comment by lea-hagen** [comment]
I just confirmed that all of the `logL = -9.999` sources are in the cluster of faint objects, so it can be used as a way to filter them out.

Putting the radius 16th/50th/84th percentiles into more useful units, I'm even less certain about what they are.  Does the model grid do anything with supernovae, binary evolution, etc?
```
radius (solar): 3.88e-07 2.14e-06 2.49e-06
radius (km): 0.27 1.49 1.73
```

**Comment by karllark** [comment]
Those are very small stars!  We should debug as the radius is a computed quantity from the isochrones.  I see an if statement and some screen output in the future for this issue.  Maybe @lcjohnso has some insight here.

**Comment by lea-hagen** [comment]
I checked the isochrone file, and there are `logL = -9.999` objects in it.  The things they all have in common, and are exclusive to them, are:
* `stage = 9` (I'm not sure where to check what that means)
* bolometric magnitude of 29.767 (the "real" stars have values brighter than ~13)

**Comment by lea-hagen** [comment]
The analysis I've done so far has all been using the SMIDGE grids.  I did a search through all of the isochrones I've ever downloaded and checked whether -9.999 was present, and here is the relevant part:
```
2017-12-30: no
2017-12-30: no
2018-5-1: yes
2018-5-24: yes
```
So apparently this became an issue sometime in early 2018.  If someone has isochrone files from around that time, we could narrow down the date a bit more.  There's probably a place to check what updates were made to the isochrones at around that time.
