### ISSUE TITLE
Add  command line functionality

### ISSUE THREAD

**Issue by s-goldman** [BEAST-Fitting/beast#315]
Current pip installation installs to a directory like: /Users/sgoldman/anaconda2/envs/astroconda/lib/python3.5/site-packages. 

By adding entrypoints and using argparse we can use a command like:

     `beast plot_cmd.py --mag1_filter='F475W'`

To get the plotting results from any directory

Will need to add defaults in arguments of plotting functions, and add the entrypoints to the setup.py file.

**Comment by s-goldman** [comment]
adding the following to the setup.py script gets the arguments (of this one example) into a parser :

```
arg_specs = inspect.getfullargspec(plot_cmd.plot)

parser = argparse.ArgumentParser()
for j, individual_args in enumerate(arg_specs.args):
    parser.add_argument(individual_args)
```

but actually adding them (the following) does not work:

`args = parser.parse_args()`

This should add the entry point but how the (args) fits in is unclear:

```
entry_points = {'console_scripts': [
    'plot_cmd = beast.plotting.plot_cmd:plot(args)
]
}
```

I still need to loop over the plotting scripts but I still do not understand how the arguments are added to the entry points. 

@eteq

**Comment by s-goldman** [comment]
How to also add either the user arguments or the defaults `arg_specs.defaults` is also confusing to me.

**Comment by s-goldman** [comment]
#336

**Comment by karllark** [comment]
Closing this issue as the work is being tracked in #336.  Please reopen if this is incorrect.
