### ISSUE TITLE
Sparse grid selection and downstream use

### ISSUE THREAD

**Issue by ktchrn** [BEAST-Fitting/beast#317]
https://github.com/BEAST-Fitting/beast/blob/7b06c434ecaedc58549eefa6588e16152efd3a7d/beast/fitting/fit.py#L502

One of the intended uses of the sparse grids is to evaluate integrals in the _megabeast_. The sparse grid provides the likelihood term, the _megabeast_ provides a (new, hierarchical) prior term. The plan seems to be to use the actual likelihood values in these computations. 

The issue is that if you select sparse grid points in a way that is proportional to the likelihood, this likelihood term will be in both the stored likelihood values and in the distribution of the points. Using both the distribution of points and the likelihood values means integrating the (likelihood * likelihood). 

The solution would be either (1) selecting points in a way that is not proportional to their likelihoods, (2) not using the weights in integral evaluation, or (3) an interpolation between the two (e.g. select points with weights sqrt(likelihood), use weight sqrt(likelihood) in integral evaluation).

**Comment by karllark** [comment]
Can you suggest which way to go?  Maybe a PR?  Naively, I would think the 1st option would be the most straightforward to implement.

**Comment by karllark** [comment]
We are already using 1.  Closing.
