### ISSUE TITLE
PHAT_SMALL example ASTs do not have rates

### ISSUE THREAD

**Issue by benw1** [BEAST-Fitting/beast#331]
Index(['F110W_IN', 'F110W_VEGA', 'F160W_IN', 'F160W_VEGA', 'F275W_IN',
           'F275W_VEGA', 'F336W_IN', 'F336W_VEGA', 'F475W_IN', 'F475W_VEGA',
            'F814W_IN', 'F814W_VEGA'],
         dtype='object')

Traceback (most recent call last):
  File "./run_beast.py", line 169, in <module>
    absflux_a_matrix=datamodel.absflux_a_matrix)
   File 
"/astro/apps7/opt/AstroConda/envs/astroconda/lib/python3.5/site-packages/beast/observationmodel/noisemodel/generic_noisemodel.py", 
line 85, in make_toothpick_noise_model
    cfilt.split('_')[-1].upper() + '_RATE')
  File 
 "/astro/apps7/opt/AstroConda/envs/astroconda/lib/python3.5/site-packages/beast/external/eztables/table.py", 
  ine 348, in set_alias
      assert (colname in self.colnames), "Column %s does not exist" % 
  colname
AssertionError: Column F275W_RATE does not exist

**Comment by drvdputt** [comment]
This is because of #330. The use_rate option should be set to False, so that the vega magnitudes are used instead. 

The commit did adjust this this for run_beast.py of the phat_small example, so you'd have to reflect that change in whichever version of run_beast.py you're using.

**Comment by karllark** [comment]
Same comment as @drvdputt.  @benw1 : are you using an old version of the phat_small example?  The newest should work.

**Comment by benw1** [comment]
This is the version that installs with:
pip install git+https://github.com/BEAST-Fitting/beast.git
I don't see a use_rate option in run_beast.py

**Comment by karllark** [comment]
I did a completely fresh install of the v1.x branch (identical to the master branch right now) and I did not have this problem.  I copied the run_beast.py and datamodel.py from the branch into a clean directory and added the data directory from the phat_small example.  It ran fine with no errors.   So, this should work for you as well.   I'm guessing you had an older version of the run_beast.py/datamodel.py files that you were using.  I'm going to close this issue, but please reopen if you are still having this problem.
