### ISSUE TITLE
run_beast.py has bad calls to pick_models and pick_positions

### ISSUE THREAD

**Issue by benw1** [BEAST-Fitting/beast#332]
(astroconda) bash-4.2$ ./run_beast.py -a
Auto-detected type: fits
Auto-detected type: fits
Auto-detected type: hd5
Auto-detected type: fits
Traceback (most recent call last):
  File "./run_beast.py", line 144, in <module>
    N_stars=N_models, Nrealize=Nrealize)
TypeError: pick_models() missing 1 required positional argument: 'mag_cuts'
(astroconda) bash-4.2$ 

This error is because the call is missing filters:

       pick_models(modelsedgrid, mag_cuts, Nfilter=Nfilters,
                    N_stars=N_models, Nrealize=Nrealize)

It can be fixed by adding the filters to the call:

        pick_models(modelsedgrid, datamodel.filters, mag_cuts, Nfilter=Nfilters,
                    N_stars=N_models, Nrealize=Nrealize)

It is also being sent the SED grid object, when what it needs is the SED grid hdf5 file

It is also missing the output filename
The following call works:
filename = datamodel.project+'/'+datamodel.project+'_inputAST.txt' pick_models(modelsedgridfile, datamodel.filters, mag_cuts, Nfilter=Nfilters,N_stars=N_models, Nrealize=Nrealize, outfile=filename)

pick_positions is not getting the catalog.  It is getting:

 pick_positions(filename,separation)

what it needs is

pick_positions(catalog, filename, separation, refimage=None)

Where catalog is the observing catalog.

The following call works:

 pick_positions(obsdata,filename,separation)

**Comment by karllark** [comment]
It would be great if you could put in a pull request with these fixes.  No worries if you don't want to - having them in an issue is great, just figured I'd ask.  :-)

**Comment by karllark** [comment]
@lea-hagen : have you had this problem when generating AST inputs?  Can you confirm/check?

**Comment by lea-hagen** [comment]
I just took a quick look at the version I'm using.  I have the format that @benw1 suggests as the fix.  I guess the `run_beast` called in that command hasn't been properly updated as we've changed the AST code.

**Comment by karllark** [comment]
The run_beast.py files in the examples directories have been updated and should now work so will close this issue.

@benw1 :  please try the new run_beast.py and reopen this issue if it is still a problem.
