### ISSUE TITLE
The new user interface

### ISSUE THREAD

**Issue by s-goldman** [BEAST-Fitting/beast#336]
There needs to be a rework of the beast user interface. We can use an entry point but it needs to point to a new python script that has arguments to run other scripts.

To run the beast we should be able to initiate commands outside of python using:
    `beast `
    `beast production`
    `beast plot_figs`
     etc.

Adding this new script to the entry point requires changing entry_points in setup.py, i.e.:

`entry_points = {'console_scripts': ['beast = beast.new_script.main:']}`

**Comment by karllark** [comment]
Need to split up the 'run_beast' script to the component parts.
E.g. something like (with the appropriate command line arguments),
- `beast create_physmodel`
- `beast calc_astinputs`
- `beast create_obsmodel`
- ` beast trimmods`
- `beast fit`

**Comment by karllark** [comment]
May need to look over the scripts in the tools directory and do some renaming to a common convention.

**Comment by s-goldman** [comment]
I still need to figure out how to pass arguments through this entry points. @eteq do you know where I can find some examples. I looked at how pip does it, and they have a [main parser script](https://github.com/pypa/pip/blob/master/src/pip/_internal/cli/main_parser.py), but it sounded like all we really need is a couple lines.

**Comment by eteq** [comment]
It looks like pip has their own trick to do that here (which I think predate `argparse`'s inclusion of these feature). 

Before I answer, just to be sure I'm understanding the question, you mean the "subcommand" thing of doing `beast create_physmodel` and `beast calc_astinputs` as separate functions, right @s-goldman ?

**Comment by s-goldman** [comment]
@eteq I'll defer to your wisdom on this but yeah that's what I had in mind. A `beast *script* -args` for each command.

**Comment by s-goldman** [comment]
@eteq The problem I can't seem to overcome is passing the argparsed arguments to the inputs of the various functions we are trying to call, when the number of arguments changes and some are optional. There must be a better way than loads of conditional statements.

**Comment by s-goldman** [comment]
The main.py file

```
import argparse
import beast

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("script", help="script selection", default="")
    parser.add_argument("--option1", help="option number 1")
    args = parser.parse_args()
    if args.script == 'fit':
        beast.run_beast.run_fitting.fitting()
    if args.script == 'create_obsmodel':
        beast.run_beast.create_obsmodel.create_obsmodel()
    if args.script == 'create_physicsmodel':
        beast.run_beast.create_physicsmodel.create_physicsmodel()

if __name__ == '__main__':
    main()
```

**Comment by karllark** [comment]
This may help.

https://docs.python.org/3/library/argparse.html#partial-parsing

**Comment by eteq** [comment]
@s-goldman @karllark - I'd suggest using the "sub-command" option argparse provides - it's documented here: https://docs.python.org/3/library/argparse.html#sub-commands .  That allows sub-commands like `beast X ...`/`beast Y ...` where X and Y have different sets of arguments.

I don't have an immediate "production" example that I know of that uses it, but it looks like it's well-suited to our case here (and I've used it myself, although admittedly for a much simpler application that's basically the same as the example in the docs itself).

**Comment by eteq** [comment]
Note, I added an example of how one might use the sub-commands thing along with the `inspect` module here: https://github.com/eteq/beast/tree/subcommand-example

it's not actually integrated with the beast, just a "toy example" using two files at the root of the repo (the ones called `deleteme_*.py`), but starting from there hopefully the rest can be finished out.

**Comment by s-goldman** [comment]
I think i've gotten it to work with a couple commands, however, now there is the problem of importing modules. While in the main beast directory for example, if I want to run plot_cmd in "plotting", it cannot import beastplotlib. This may be a quick fix, but may also mean changing to absolute imports for the entire beast. Any thoughts on this @karllark?

**Comment by karllark** [comment]
If we need to do absolute imports to get this working, that is fine with me.  Probably better this way anyway.
