### ISSUE TITLE
Instructions for BEAST example run are unclear

### ISSUE THREAD

**Issue by Stargrazer82301** [BEAST-Fitting/beast#347]
In the "Running Example" section of the documentation, it says:

> Now try a sample BEAST run:
>`$ ./run_beast.py`
>or:
>`$ python run_beast.py::`

This implies that these commands are what are required to launch a BEAST run. However, these commands are merely to print the help message to screen. So perhaps clarify that switches -potf are needed to actually launch a run.

**Comment by Stargrazer82301** [comment]
Also, the switches will not work if run via `python run_beast.py -potf`. They can only be called via `./python run_beast.py -potf`.

**Comment by Stargrazer82301** [comment]
Bulk of this fixed in b0a7d43a4e801c2773269284c3d315619f888aad. Although switches still require ./python etc.

**Comment by karllark** [comment]
Going to close this issue as it looks to be basically addressed.  Additional work is happening on the install instructions and that will likely clean up things.  Please reopen this issue if it does not.
