### ISSUE TITLE
discrepancies in how extinction is handled by BEAST code and dust_extinction

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#359]
The BEAST has several built-in extinction curves ([here](https://github.com/BEAST-Fitting/beast/blob/master/beast/physicsmodel/dust/extinction.py)).  When input wavelengths are outside of their defined ranges, they return 0.

We've recently started switching over to the `dust_extinction` package (#259, #300).  Unlike the BEAST implementation, these exit with an error when wavelengths are outside the allowed range.

The effect of this: the stellar grids extend over a wide range of wavelengths, so when we run `make_extinguished_sed_grid`, code that used to work fine is now not working.  We've been fine in the past because our filter sets don't overlap the wavelengths where extinction curves are undefined, but this is something that should be fixed.

In the short term, we want to use `F20` from `dust_extinction` for v1.3 production runs.  I see three options (though there are perhaps more):
1. Edit `Generalized_DustExt` to have an option to return 0 for wavelengths where `dust_extinction` says the curve is undefined.
2. Edit the creation of the stellar grids such that they don't extend beyond where the extinction curve is defined.
3. Implement F20 in the BEAST's extinction curve file, and allow 0 extinction where the curve is undefined, thus temporarily not using `dust_extinction` at all.

@karllark and @lcjohnso - you may have thoughts about this.

**Comment by karllark** [comment]
I favor 1 or 2.  Avoids having to maintain F20 in the BEAST.

1. Could be done as all the dust_extinction models include the allowed wavelength range as part of the model.  E.g. mod = F20(), F20.x_range where x_range is in units of 1/micron (yeah would be better at microns I know).

2. Probably the cleanest and most robust solution.  Kinda worrying to have SEDs created that have silently not applied dust extinction outside of the range defined for the extinction model.

**Comment by lea-hagen** [comment]
I also like 2 the best.  I haven't worked with that part of the code before, though.  If someone else can easily make that change, that would be great... otherwise I can take a look.
