### ISSUE TITLE
TypeError: __setitem__() takes 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by benw1** [BEAST-Fitting/beast#365]
I'm getting an error when attempting to generate a physics model:

(astroconda) bash-4.2$ run_beast.py -p
Auto-detected type: fits
Auto-detected type: fits
Interrogating http://stev.oapd.inaf.it...
Downloading data...http://stev.oapd.inaf.it/tmp/output788546302662.dat
Interrogating http://stev.oapd.inaf.it...
Downloading data...http://stev.oapd.inaf.it/tmp/output967397366956.dat
Interrogating http://stev.oapd.inaf.it...
Downloading data...http://stev.oapd.inaf.it/tmp/output362610211203.dat
Interrogating http://stev.oapd.inaf.it...
Downloading data...http://stev.oapd.inaf.it/tmp/output577784349517.dat
Interrogating http://stev.oapd.inaf.it...
Downloading data...http://stev.oapd.inaf.it/tmp/output183910956912.dat
Interrogating http://stev.oapd.inaf.it...
Downloading data...http://stev.oapd.inaf.it/tmp/output719742725211.dat
Interrogating http://stev.oapd.inaf.it...
Downloading data...http://stev.oapd.inaf.it/tmp/output279374583465.dat
ngc2203_beast/ngc2203_beast Isochrones
Auto-detected type: csv
Make spectra
applying 1 distances
Adding spectral properties: True
spectral grid:|##############################################| 46031/46031 100% [time: 00:22, eta: 00:00, 2031.63 iters/sec]
Traceback (most recent call last):
  File "./run_beast.py", line 93, in <module>
    add_spectral_properties_kwargs=extra_kwargs)
  File "/astro/apps7/opt/AstroConda/envs/astroconda/lib/python3.5/site-packages/beast/physicsmodel/model_grid.py", line 194, in make_spectral_grid
    for gk in g:
  File "/astro/apps7/opt/AstroConda/envs/astroconda/lib/python3.5/site-packages/beast/physicsmodel/creategrid.py", line 80, in gen_spectral_grid_from_stellib_given_points
    yield osl.gen_spectral_grid_from_given_points(pts, bounds=bounds)
  File "/astro/apps7/opt/AstroConda/envs/astroconda/lib/python3.5/site-packages/beast/physicsmodel/stars/stellib.py", line 1131, in gen_spectral_grid_from_given_points
    dtype=np.int64)
TypeError: __setitem__() takes 2 positional arguments but 3 were given
(astroconda) bash-4.2$ ls ngc2203_beast/

**Comment by karllark** [comment]
Can you share your datamodel.py file?  That might help understand the issue.

**Comment by benw1** [comment]
[datamodel.py.txt](https://github.com/BEAST-Fitting/beast/files/3510672/datamodel.py.txt)

**Comment by mfouesneau** [comment]
Could it be caused by the new Parsec website? Or the interface has been updated?

**Comment by benw1** [comment]
Looks like the problem is related to starting the age with 8.5. 
This line leads to the error:
logt = [8.5, 10.13, 0.05]
This line does not:
logt = [8.0, 10.13, 0.05]

**Comment by karllark** [comment]
Weird.  I wonder why that is the case?  I would have not thought  this would cause that kind of problem.  More investigation needed.  @lea-hagen ?
