### ISSUE TITLE
generating artificial stars with subgrids

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#374]
The artificial stars for ASTs are chosen by randomly selecting SEDs from the physics model grid.  If we use the flux bin method (see discussions in #308 and #327), we need to read the entire physics model grid into memory, which is generally not possible for production runs.  I see two options:
1. We create a smaller physics model grid (same min/max, but coarser sampling) that only gets used for making the artificial star list.  I'm not sure if this would cause any problems later (either in the BEAST or MegaBEAST).
2. A possibility with XSEDE: We *do* create a full physics model grid, in addition to making subgrids.  We use the whole physics model grid only when making the artificial star list, and then use subgrids for all other steps of the BEAST running/fitting.

**Comment by karllark** [comment]
Option 1 seems like a good solution.  A coarser grid should work fine with a minimal (more maybe no) impact on the total number of AST stars.  One positive, this is a solution that can be done now and with local resources.

**Comment by karllark** [comment]
Ok to close this issue?  I feel like this was more a question and I think it has been answered.  Especially with the workflow instructions now (soon! PR #415) mentioning that ASTs might be run with a coarser grid.

**Comment by lea-hagen** [comment]
I've been going with Option 1 (coarser grid).  Since that doesn't seem to be problematic for anything, I think it's fine to close this.
