### ISSUE TITLE
pip install v1.3 is out of date

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#375]
I just created a new environment and did `pip install beast==1.3`, following the instructions [here](https://beast.readthedocs.io/en/latest/workflow.html#production-conda-environment).  I attempted to import code added in #364, but it didn't work.  So I navigated into the installed code (`~/.conda/envs/beast_v1.3/lib/python3.6/site-packages/beast/`) and discovered that the newest files aren't there.  Also, the `examples` directory is empty, but that might not be related.  Anybody else having the same situation for the v1.3 release?

**Comment by karllark** [comment]
That is odd.  When I check the v1.x branch, those files are there and the example directory is not empty.  But when I download the tar.gz file from pypi, those files are not there.  Argh.  I'm not sure what went wrong.  I'll work on it now.

**Comment by karllark** [comment]
I found the problem.  The new `beast/tools/run/` directory did not have an `__init__.py` file.  As a result, that directory is not included in the build.  This is the same reason the examples directory is empty.  Argh.  I'm going to add __init__.py files to all those directories and tag a new release.  This release will be v1.3.2 as I only figured this out after doing a v1.3.1 release.  Exciting times!

**Comment by karllark** [comment]
Ok.  I just uploaded the v1.3.2 release to pypi.  Give the pip install a try and tell me how it goes.

**Comment by lea-hagen** [comment]
That fixed it.  Thanks!

**Comment by karllark** [comment]
Yeah.
