### ISSUE TITLE
Tools in tools/run subdirectory will not all run

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#382]
Undefined variables/functions identified via flake8.  Need fixing/testing.

./run/make_ast_inputs.py:82:13: F821 undefined name 'modelsedgrid_filename'
./run/make_ast_inputs.py:98:13: F821 undefined name 'modelsedgrid_filename'
./run/make_ast_inputs.py:119:17: F821 undefined name 'pick_positions_from_map'
./run/make_ast_inputs.py:133:17: F821 undefined name 'pick_positions_from_map'
./run/helper_functions.py:57:28: F821 undefined name 'gen_subgrid'

**Comment by lea-hagen** [comment]
Forgot to add in #400 that it fixes this issue.
