### ISSUE TITLE
using Shapely/GEOS for processing regions

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#397]
There are a few places where we need to evaluate the overlaps of regions.  Some examples:
* finding where some subsets of filter overlaps exist in an image
* determining whether a source density pixel is within a region (e.g., for dropping ASTs on the image)
* for image edges, calculating the area for a source density (#390)

So far, we've been using matplotlib `Path` objects. The types of operations we want to do are only partially implemented by `Path`, so some of the code has been a bit clunky.  Now I'm running into cases where `Path` can't solve my problems.

The GIS community has a package called [Shapely](https://shapely.readthedocs.io/en/stable/project.html) (which is a python wrapper for [GEOS](https://git.osgeo.org/gitea/geos/geos.git)), and it does all sorts of fancy polygon manipulations.  It looks like it would be perfect for some stuff I'm working on, but since it's another package to install, I wanted to check here before adding a dependency.

**Comment by karllark** [comment]
I'm fine with adding a dependency for this.  Especially if it makes what we need to do easier!
