### ISSUE TITLE
Plotting scripts tests

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#417]
Need more tests for plotting scripts.  One exists for plot_indiv_fit (see tests subdir of plotting).  Should be straightforward to generate tests based on data already available for download (http://www.stsci.edu/~kgordon/beast/). 

Some specific scripts needing tests that should be straightforward:
- [ ] plot_cmd.py
- [ ] plot_cmd_with_fits.py
- [ ] plot_filters.py

**Comment by cmurray-astro** [comment]
working on this! Connected to PR #428, still a work in progress.

**Comment by karllark** [comment]
Closed by #428.
