### ISSUE TITLE
Missing exit() imports

### ISSUE THREAD

**Issue by lcjohnso** [BEAST-Fitting/beast#427]
A quick search showed that `exit()` is used without import from `sys` library in a number of files:

beast/fitting/trim_grid.py
beast/plotting/plot_region_diags.py
beast/observationmodel/observations.py

Quick fix: add `from sys import exit` to these files.

**Comment by karllark** [comment]
While this will solve the issue with not having exit defined - we should consider moving away from using exit (I'm probably the person who's added the most calls to this function).  We really should be raising an error or warning, but crashing out via exit.   Then the warnings/errors can be caught if desired and handled.  But that is probably different issue.

**Comment by jwuphysics** [comment]
I worked on some fixes in the spirit of "we should consider moving away from using exit". 

A few are kept in, such as in `docs/conf.py`, where it wasn't clear to me how to best crash out the program. I'll do the PR as soon as the previous one is merged.
