### ISSUE TITLE
choosing an output catalog after calculating source densities

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#434]
There has been some confusion lately over what output catalog file to use after creating a source density map.  These are the two possible files:
* `[prefix]_with_sourceden_inc_zerofluxes`: photometry catalog with an additional column that has the source density
* `[prefix]_with_sourceden.fits`: same as above, but only for sources with flux != 0 in each band

Also, the background map calculations don't do any cuts with zero fluxes, and the only output catalog is `[prefix]_with_bg.fits`, which is the full catalog with two additional columns of background numbers.

**Comment by karllark** [comment]
From reading the description, this sounds like something that needs to be added to the docs, right?  Or maybe docs plus an update to the code?

I do feel that the file names are not intuitive.  The catalog files with all the sources with the addition of source density or background should be the [prefix]_with_[sourceden|bkg].  Then the files that remove the sources with flux!= 0 in any band should be named [prefix]_with_[sourceden|bkg]_wo_zerofluxsources - or something like that.  At least that is my 2 cents.

**Comment by lea-hagen** [comment]
Agreed on the name changes.  

There's also the question of which one to use going forward with science.  I don't recall from our conversation last week whether we decided the flux=0 sources ought to be dropped or not (or perhaps we didn't reach a conclusion yet).

**Comment by karllark** [comment]
I think we should not fit the sources with zero fluxes in one or more bands.  This zero flux means that the source was likely just not covered by the observations in that band.  Hence the selection function will be different.  This will impact the noise model including completeness.

**Comment by lea-hagen** [comment]
Here are a couple maps from a METAL field:
* Left: source density map (linear scaled).  The code does not remove any catalog sources with zero flux before calculating the source density.
* Right: map of number of sources with flux=0 in at least one band (**log scaled**).  These sources are currently excluded from the `[prefix]_with_sourceden.fits` catalog.

<img width="884" alt="zero_fluxes" src="https://user-images.githubusercontent.com/32465297/67972406-0155e600-fbe5-11e9-9565-fd5375d15925.png">

My thoughts based on those maps (which are of course open for discussion!).
* The zero flux cut is excluding some sources in the overlapping region.  It's not a huge number (up to 10 in a 5" pixel), but there's apparently something else going on.
* There's code (`cut_catalogs.py`) in the workflow that explicitly allows us to cut based on flags, filter overlap, or both.  I would argue that it's better to keep the catalog trimming there rather than in the source density map code.

**Comment by karllark** [comment]
So, are you proposing to remove the "wo_zerofluxes" output from this step?  I think this is a good idea.  Better to do it once in cutting catalogs and then use that catalog for all other work including source density measurements.

**Comment by lea-hagen** [comment]
Alright, then let's do it!  Should making that change be a new issue?

**Comment by karllark** [comment]
Nope.  The PR should just reference this issue as that is where the discussion is.
