### ISSUE TITLE
parameter recovery tests

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#435]
I'm looking to create a version of [Fig 13 in Gordon+16](http://www.astroexplorer.org/details/apjaa2ee4f13), which shows how well physical parameters from an SED are recovered, for a given noise model.  I'm not sure if this is encompassed by the sensitivity tests (#106/#248) that already exist, or if those are specifically for simulating which filters affect parameter constraints.

**Comment by karllark** [comment]
I think simulating the photometry work has been done.  But not the plotting the results and making the figure.   Would be great to have code for that.  I can point people in the direction of where the code that made the figure in the paper may be (central storage) if that would help.

**Comment by lea-hagen** [comment]
Yes, that would help!  Thanks!

**Comment by karllark** [comment]
I think.../astro/dust_kg/harab/beast/projects/sensitivity_tests/figs.py.
