### ISSUE TITLE
problems reading in symbolic link

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#440]
As part of doing parameter recovery tests, I've made symbolic links to physics/noise models, so that they don't have to be duplicated into the new folder.  The `FileSEDGrid` function doesn't seem able to read in those files.

```
> sed_file = './14675_LMC-5665ne-12232_sim/14675_LMC-5665ne-12232_sim_seds.grid.hd5`
> os.path.isfile(sed_file)
False
> os.path.islink(sed_file)
True
> FileSEDGrid(sed_file)
[lots of traceback]
OSError: ``./14675_LMC-5665ne-12232_sim/14675_LMC-5665ne-12232_sim_seds.grid.hd5`` does not exist
```

**Comment by karllark** [comment]
This is odd.  I have not had this problem in the past.  I do not understand why this does not work.  Interesting that python knows that the file is a link not a file.  The link is correctly pointing to the right file, right?  Just asking to be sure.

**Comment by lea-hagen** [comment]
I poked at the traceback and this seems to be the relevant part in pytables:
```
/user/lhagen/miniconda3/envs/bdev/lib/python3.6/site-packages/tables-3.5.2-py3.6-linux-x86_64.egg/tables/utils.py in check_file_access(filename, mode)
    155         # The file should be readable.
    156         if not os.access(filename, os.F_OK):
--> 157             raise IOError("``%s`` does not exist" % (filename,))
    158         if not os.path.isfile(filename):
    159             raise IOError("``%s`` is not a regular file" % (filename,))
```
So the problematic check is with [`os.access`](https://docs.python.org/3/library/os.html#os.access).  That documentation says it should be able to follow symlinks (which is the default), but I can't get it to return anything other than `False`.  That's even with the most lenient file permissions (`rwx` for all).

**Comment by lea-hagen** [comment]
Oh wait, I think there is a problem with the link itself....  I'll investigate and close if so!

**Comment by lea-hagen** [comment]
Yep, that was the problem.  Lesson for my future self: be careful with `os.symlink`!

**Comment by karllark** [comment]
Yeah!
