### ISSUE TITLE
Adjustable distance prior

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#45]
There is no distance prior.  Issue #38 will add a way to have distance as a fit parameter.  But with a flat prior.  We should have an adjustable distance prior.

Better would be to have the form and necessary variables set in the datamodel.py file or something else. Something else may be better for eventual use by the megabeast.

Two motivations.

Provide flexibility for the input of the distance prior for BEAST runs
Provide flexibility for the eventual use of the BEAST distance model by the MegaBEAST

**Comment by drvdputt** [comment]
In case someone starts working on this, I want to bring up the following:

The beast has some code in grid_weights.py to deal with irregular grid spacings. E.g. for Z, the prior in bin-space is set equal to the the bin widths (based on the middles between the grid points in linear space). When summing over the grid, this corresponds to a flat prior in Z-space (sum becomes an integral)

When I implemented the distance parameter, I did not apply these weights to the distance (d), and so the weight is 1 for each bin, so the prior is flat in bin-space. So in d-space, we currently always have a 1/bin_width prior.

For a log-spaced distance grid this makes sense. If you do the math for this specific case, you can find that the bin width (however you calculate it) is a constant times the center value of the bin. So the prior is 1/d in d-space, which is flat in log(d)-space.

In any case, it would be better to just apply the same correction as for Z, and have a 1/d prior explicitly as an option.
