### ISSUE TITLE
Saving 2D PDFs

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#472]
We've been trying to solve #373 (evaluating the probability of different stellar types) using the log likelihoods - either calculating probabilities during the BEAST run, or saving enough to evaluate afterwards.  Both have significant disadvantages (see discussions in #373, #467, #468).  

Another option I'm investigating is saving 2D PDFs.  It'll require a fair bit of disk space, so if we decide to go this route, we should decide what quantities are worth saving.  To start, here's a list of parameters (from one of the METAL fields) that get 1D PDFs:
```
['Av',
 'M_act',
 'M_ini',
 'Rv',
 'Rv_A',
 'Z',
 'distance',
 'f_A',
 'logA',
 'logHST_ACS_WFC_F475W_nd',
 'logHST_ACS_WFC_F475W_wd',
 'logHST_ACS_WFC_F814W_nd',
 'logHST_ACS_WFC_F814W_wd',
 'logHST_WFC3_F110W_nd',
 'logHST_WFC3_F110W_wd',
 'logHST_WFC3_F160W_nd',
 'logHST_WFC3_F160W_wd',
 'logHST_WFC3_F225W_nd',
 'logHST_WFC3_F225W_wd',
 'logHST_WFC3_F275W_nd',
 'logHST_WFC3_F275W_wd',
 'logHST_WFC3_F336W_nd',
 'logHST_WFC3_F336W_wd',
 'logL',
 'logT',
 'logg',
 'mbolmag',
 'radius']
```
I don't think we'd need any of the flux-related quantities.  Among the other physical parameters, are there any that we can definitely ignore, or any pairs that are unlikely to ever be useful?

**Comment by karllark** [comment]
In helping decide which 2D pPDFs to save, it would be useful to know what these will be used for.  What is the science goal/question for which such information is needed?

**Comment by lea-hagen** [comment]
The idea is to be able to make cuts in two parameters to evaluate the probability of a particular stellar type.  For instance, if you wanted the probability that your source is an O star, you could integrate the `M_ini` 1D PDF between the relevant masses, and normalize by the total.  But if you wanted the probability that it's a good candidate for extinction curves, you'd need to integrate within the `M_ini - A_V` 2D PDF.

**Comment by karllark** [comment]
Ok.  You've made an argument for 1 2D pPDF.  Are there others we need for similar reasons?  Or are you thinking to make the *all* just in case?  Just trying to better understand the question.  :-)

**Comment by lea-hagen** [comment]
Well, that's actually part of my question.  I like the "all just in case" idea, but I want to balance that against the larger amounts of storage space, particularly if some of them are definitely not useful.  I would guess that the `logL - mbolmag` combo, for example, won't ever be useful.

**Comment by karllark** [comment]
Maybe just limit the 2D pPDFs to just the 7 core BEAST parameters.  In theory, the probability of object can be determined from those 7 parameters as all the rest can be derived from them.
