### ISSUE TITLE
docs: make list of papers using the BEAST

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#473]
We should add something to the docs that lists papers that use the BEAST.

**Comment by karllark** [comment]
Papers that cite the BEAST paper is a good place to start.  I don't think most of them actually use the BEAST, so reading them is needed.

https://ui.adsabs.harvard.edu/abs/2016ApJ...826..104G/citations

**Comment by karllark** [comment]
https://ui.adsabs.harvard.edu/abs/2020arXiv201007273L/abstract
https://ui.adsabs.harvard.edu/abs/2020ApJ...902...54C/abstract
https://ui.adsabs.harvard.edu/abs/2020arXiv201011181Y/abstract
https://ui.adsabs.harvard.edu/abs/2019ApJ...871..151R/abstract
https://ui.adsabs.harvard.edu/abs/2018ApJ...855..133K/abstract
https://ui.adsabs.harvard.edu/abs/2017ApJ...838...47Y/abstract
https://ui.adsabs.harvard.edu/abs/2017ApJ...847..102Y/abstract

**Comment by karllark** [comment]
https://ui.adsabs.harvard.edu/abs/2017ApJ...850...86D/abstract
https://ui.adsabs.harvard.edu/abs/2017IAUS..329..376D/abstract
https://ui.adsabs.harvard.edu/abs/2018ApJ...862...28L/abstract
https://ui.adsabs.harvard.edu/abs/2018MNRAS.478.5017R/abstract
https://ui.adsabs.harvard.edu/abs/2020ApJ...888...22V/abstract

**Comment by galaxyumi** [comment]
https://ui.adsabs.harvard.edu/abs/2020AJ....159..119P/abstract

**Comment by mdecleir** [comment]
I have added a list of papers in PR #670 . It is not complete yet.
