### ISSUE TITLE
missing input parameters in the phat examples

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#484]
For the phat_small and phat_small_multidistance examples, the 'as_n_flux_bins' and  'ast_n_per_flux_bins parameters in their datamodel.py files are missing.

**Comment by karllark** [comment]
Please raise this issue on https://github.com/BEAST-Fitting/beast-examples as that is where the examples live now.

**Comment by galaxyumi** [comment]
Done!
