### ISSUE TITLE
Test collection fails for python 3.5

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#485]
Travis tests are failing on python 3.5 - due to some issue with photutils.  The error is below.  Seems like this is an issue with photutils, but not 100% sure.  @lea-hagen as this is code you added (I think) maybe you have info?

`==================================== ERRORS ====================================
________ ERROR collecting beast/tools/create_background_density_map.py _________
beast/tools/create_background_density_map.py:22: in <module>
    import photutils as pu
.eggs/photutils-0.7.2-py3.5-linux-x86_64.egg/photutils/__init__.py:19: in <module>
    from .aperture import *  # noqa
.eggs/photutils-0.7.2-py3.5-linux-x86_64.egg/photutils/aperture/__init__.py:7: in <module>
    from .circle import *  # noqa
.eggs/photutils-0.7.2-py3.5-linux-x86_64.egg/photutils/aperture/circle.py:13: in <module>
    from .core import PixelAperture, SkyAperture
.eggs/photutils-0.7.2-py3.5-linux-x86_64.egg/photutils/aperture/core.py:104: in <module>
    class PixelAperture(Aperture):
.eggs/photutils-0.7.2-py3.5-linux-x86_64.egg/photutils/aperture/core.py:369: in PixelAperture
    subpixels=5, unit=None):
/home/travis/miniconda/envs/test/lib/python3.5/site-packages/astropy/utils/decorators.py:445: in decorator
    '.'.format(new_name[i]))
E   TypeError: "None" was not specified in the function signature. If it was meant to be part of "**kwargs" then set "arg_in_kwargs" to "True".
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 1.09 seconds ============================
The command "$MAIN_CMD $SETUP_CMD" exited with 2.`

**Comment by lea-hagen** [comment]
I had an issue with photutils once that was solved by updating astropy (this was pre-4.0).  The error looks familiar, so maybe the same one?  What version of astropy is this test using?

**Comment by karllark** [comment]
latest stable version - for python 3.5 and this looks like astropy 2.0!  https://travis-ci.org/BEAST-Fitting/beast/jobs/640061608

Does this mean the BEAST can't support python 3.5?

**Comment by karllark** [comment]
Looks like that might be the case.
http://docs.astropy.org/en/stable/install.html

**Comment by lea-hagen** [comment]
I've been using Python 3.6 for a while, so I'm not sure.  But looking at the last docs for astropy 3, it should work with python 3.5.
https://docs.astropy.org/en/v3.2.3/install.html

**Comment by karllark** [comment]
Interesting.  Not sure why asking for the stable version for python 3.5 is giving astropy 2 something.  Weird.

**Comment by karllark** [comment]
Probably solution is to drop support for python 3.5.  Do when addressing #541.

**Comment by karllark** [comment]
Closing as we no longer support python 3.5.
