### ISSUE TITLE
log(L) = -9.999 model points in the isochrones

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#486]
There are some logL = -9 models in the PARSEC isochrones, and it is unclear what they are. I emailed Leo Girardi about this. 
![logL_minus9](https://user-images.githubusercontent.com/5504376/72839971-46783a00-3c61-11ea-937c-f5fa6ff3889f.png)

**Comment by lea-hagen** [comment]
I've stumbled across those too (#308/#309).  I don't think we figured out what they were.

**Comment by galaxyumi** [comment]
I got a reply back from Leo. He said "The points of logL=-9 are intentionally included to mark the end of the isochrones, or to mark sections of isochrones that should be considered as not populated." He also pointed out [this page](http://stev.oapd.inaf.it/cmd_3.3/faq.html) for a short explanation. 

So we are safe to exclude those points!

**Comment by karllark** [comment]
Good to understand that origin of these.  And that we should exclude them.  Do we currently exclude them in the get_isochrone stage of the BEAST?  I don't think so and clearly we should.

**Comment by galaxyumi** [comment]
We currently exclude them when selecting AST inputs, meaning that they made to the generating SED grid stage! I am not sure if we want to cut out something in the get_isochrone stage. We can cut out things when generating spec grid.

**Comment by karllark** [comment]
Cutting them when generating the spec grid sounds like the right way to go.
