### ISSUE TITLE
Optimizing AST selection with the toothpick method 

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#497]
Current way to select AST inputs with the toothpick method work totally fine. But there is a room for improvement. We can optimize the selection algorithm for filling flux bins by making it select the SEDs that fill the flux bins in other filters most efficiently. In terms of speed, it might not be very beneficial, but this method would select SEDs in a more uniform way.

**Comment by galaxyumi** [comment]
Currently we might select more than enough ASTs at the bright- and faint-ends by requiring roughly same number of ASTs in each flux bin. Because there are not many models in the bright- and faint-ends, the same models are picked multiple times. See an example plot below. 

![All_model_grid_UGCA292](https://user-images.githubusercontent.com/5504376/79779593-9cb05400-8308-11ea-95cb-195e1ea6b8d2.png)

**Comment by karllark** [comment]
Can you add a bit more info on what I should be seeing this plot?

**Comment by galaxyumi** [comment]
In the AST Hess diagram (right panels), you can see more ASTs are populated in the bright and faint ends where we are going to have roughly 100% completeness or 0% completeness anyway.

**Comment by karllark** [comment]
Is this a problem?

If the same model is picked (because there is no other choice), that is ok I think.  It should get a different spatial location and measurement (photon) noise.  So still good with the goal of getting a statistical measure of the offset, noise, and completeness.

**Comment by galaxyumi** [comment]
Not a problem at all! Just thinking about a way to optimize AST selection. 

Good point - they prob different spatial locations!

**Comment by karllark** [comment]
Going to close this issue as I think the answer is that the current method is ok.  Please reopen if this is not the case.
