### ISSUE TITLE
define magnitude cuts when generating AST inputs

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#502]
@lea-hagen 2 @karllark 

Is there a particular reason for defining 90 percentile of the observed mags as the faintest mags in beast/tools/run/make_ast_inputs.py? 
line 59: min_mags[k] = np.percentile(obsdata[keep][sfiltername], 90.0)

**Comment by karllark** [comment]
I can't remember why this was picked.  @lea-hagen?  I thought we went lower for the ASTs than the observed catalog.  Are we still cutting the ASTs based on the observed catalog?

**Comment by galaxyumi** [comment]
No, we are including all SEDs for the mega-BEAST completeness calculation. As we discussed, however, there should be a good portion of SEDs that will obviously have completeness=0 in all bands. Thus, by excluding those SEDs from AST selection, I think we can populate more ASTs where we care more. 

Of course, we need some tests to determine which magnitude cuts ensure removing SEDs with completeness=0 in all bands. I would like to start with 10 magnitude below the faintest observed magnitude in each band. And I saw the faintest observed magnitude was defined as the 90th percentile value of the observed magnitude distribution in the current code. I was curious whether there is a particular reason for that choice. If not, I will just use the faintest magnitude instead of the 90the percentile value.

**Comment by karllark** [comment]
I think we should use the faintest mag instead of the 90th for the purpose you describe.

I was wondering why we had been defining this mag in the code already.  I'm guessing it was left over from previous times when we were (incorrectly) cutting the ASTs at this point.  Just confirming that and you are correct that we should be using it again, for the purpose you describe.

**Comment by galaxyumi** [comment]
Issue resolved!
