### ISSUE TITLE
rename datamodel.py

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#508]
As we've had a recent wave of new users, I've heard feedback that the name `datamodel` for a file that has settings is confusing.  I propose that we rename it to something like `beast_settings` or `beast_input`.  I think it would be very straightforward to find-replace all instances of `datamodel` in the code/documentation.

**Comment by galaxyumi** [comment]
beast_settings sounds good to me.

**Comment by lcjohnso** [comment]
What about `beast_params`?

Would you consider making this a configurable name that defaults to your new choice, but allows for backward compatibility and personal configurability?  Just as easy to replace with a config variable as another hardcoded string, right?

**Comment by karllark** [comment]
Sounds a reasonable idea.  Maybe good to think ahead at what we want things to be for #320.  Don't want to have to change the name too often.  :-)
