### ISSUE TITLE
v1.x branch updates

### ISSUE THREAD

**Issue by lcjohnso** [BEAST-Fitting/beast#509]
@karllark: can you clarify what commits / PRs are (or should be) merged into the v1.x branch?

There's a blurry line between v2 enhancement and v1 bug fixing. I'm not sure what, if any, "braking" changes in v2 have occurred that require a bifurcation and use of v1.x (at least so far).

To provide explicit context: I had planned on using v1.x for SMIDGE PMS fitting to match upcoming production runs.  However, given a number of filename issues in the newly organized `tools/run` scripts (example commit here: https://github.com/BEAST-Fitting/beast/commit/e216ac397fc5cf46a51c995f9716081c01e6c5f5) and IMF prior issues (see https://github.com/BEAST-Fitting/beast/pull/387), I really need to use master/v2.x branch.  There are a number of similar issues that make the current v1.x release on pypi non-optimal and perhaps not usable.

Suggestions on how to proceed?  Once the principles are written down, perhaps they should be added to install + release docs, and/or PR template + review process?

**Comment by karllark** [comment]
This is a very good question.  At this point, there have been too many updates to v2.0 to make it easy to cherry-pick specific PRs for the 1.x branch.  There have not been any PRs that have made the v2.0 (master) branch separate from what we want for production.  So, the right way to go now is probably to rebranch from v2.0 (master) for a new production run branch.  I've tried just merging v2.0 into v1.x, but there are too many conflicts.  Might try again.

Anyway, I'll work on getting the production branch (v1.x) updated.  I definitely want to support production runs such that we can intercompare them.

**Comment by karllark** [comment]
Nominally, I should be tagging any PRs for v1.x that are bugfixes for the production branch.  This would make sure I merge those PRs into both the v1.x branch and the master branch.  I haven't been good about doing this.  Hence, I've just created a v1.4 branch for the "new" production branch (It was very non-trivial to use the current v1.x branch to do this - will be abandoned and v1.4 takes its place).

**Comment by karllark** [comment]
See #510.

**Comment by karllark** [comment]
Closing as #510 should cover things.  But please reopen if this is not correct.

**Comment by lcjohnso** [comment]
Great -- thanks, @karllark!  I like your plan to abandon the current v1.x and just start fresh with regards to an upcoming bifurcation in versions.
