### ISSUE TITLE
Update production run code (v1.4)

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#510]
I've created a new branch for the production runs called v1.4.  I will do a pip installable release of the v1.4 once there is agreement that everything is ready for such (see open PRs and issues below).

A new branch was needed as the master branch has updates needed for production, but v1.x and master have diverged so much that merging the master into v1.x produced many conflicts.  The master branch has not yet changed anything in how production runs are planned, so a new branch is the easiest way to go. 

PR/issues for v1.4:
https://github.com/BEAST-Fitting/beast/milestone/9

**Comment by karllark** [comment]
I think it is time to make v1.4.  @lea-hagen : do you agree?

One motivation is to get a tagged version before PR #553 is merged.  This PR has major changes to some of the core of the BEAST (grids).

**Comment by lea-hagen** [comment]
After starting to take a look at #553, I have mixed feelings.  It definitely feels like it warrants a new version with such large changes, but I can't claim to be the expert on versioning :).  Here are a few thoughts/questions I had while pondering this.
* Will there be a 1.4/2.0 release for beast-examples too?  Particularly since `datamodel` will be changing (https://github.com/BEAST-Fitting/beast/pull/553#issuecomment-626948624).
* Part of our motivation for making a frozen v1.4 branch was to have a particular version for production runs.  Since the changes in #553 won't change the way the production runs are done (file formats, the math, etc., are unchanged), I think it's still consistent with the METAL production runs I'm doing now.  Aside from updating datamodel.py, I'm pretty sure I could just copy over the new code mid-run and everything would be fine.
* How does testing work with two versions?  Do we need separate tests for each, or do we just write them for v2.0 and leave the corresponding v1.4 parts untested?

**Comment by karllark** [comment]
Our testing does not work with multiple versions of the cached files.  This is something we could change, but I don't know if it is worth it.

As you say, #553 does not impact the results at all.  Hence it is not needed in v1.4.  While it could go in, I am inclined not to include it as it is not needed.  v1.4 should be ready and appropriate for production runs.  v2.0 is going to have a lot of updates to the internal mechanics of the BEAST, but not as much on the results (I hope).  At least that is my reading of the current efforts for v2.0 - really working off technical debt and setting the BEAST up for easier development and maintenance in the future.

Good point about beast-examples.  We should have a matched v1.4 release as well.

**Comment by karllark** [comment]
An additional point.  #553 should not impact the BEAST results.  But it might as there are many changes.  Hence to be safe and conservative, getting a tagged release before such changes sounds like the way to go.

**Comment by lea-hagen** [comment]
I just accidentally discovered that grids generated with the changes in #553 can't be read in by the pre-#553 code.  (I was just doing some unrelated testing, so no impact on science or production runs or anything.)  So there's a good reason for keeping them separate!

**Comment by karllark** [comment]
Can you be more specific of the difference?  I'm mainly curious as I'm ok breaking things at this point.   We kinda need to rip this band-aid off so we can make larger and more useful changes.

**Comment by lea-hagen** [comment]
I didn't carefully investigate - just re-generated the grids and everything worked fine.  But it was in `FileSEDGrid`.  Here's the full traceback if you're curious.
```
Traceback (most recent call last):
  File "/user/lhagen/miniconda3/envs/bdev/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/user/lhagen/miniconda3/envs/bdev/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/tools/trim_many_via_obsdata.py", line 43, in <module>
    modelsedgrid = FileSEDGrid(modelfile)
  File "/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/physicsmodel/grid.py", line 403, in FileSEDGrid
    return SpectralGrid(fname, header=header, aliases=aliases, backend=backend)
  File "/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/physicsmodel/grid.py", line 114, in __init__
    self._backend = find_backend(backend)(*args, **kwargs)
  File "/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/physicsmodel/helpers/gridbackends.py", line 226, in __init__
    self._from_File(lamb)
  File "/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/physicsmodel/helpers/gridbackends.py", line 293, in _from_File
    self.grid = Table(fname, tablename="/grid")
  File "/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/external/eztables/table.py", line 130, in __init__
    self.read(*args, **kwargs)
  File "/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/external/eztables/table.py", line 157, in read
    t = manager().read(filename, **kwargs)
  File "/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/external/eztables/backends/hdf5backend.py", line 226, in read
    meta = self.readColDesc(node, colname)
  File "/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/external/eztables/backends/hdf5backend.py", line 193, in readColDesc
    key = key[0].replace("NAME", "")
IndexError: list index out of range
```

**Comment by karllark** [comment]
Interesting.  Looks like eztables can't read astropy written tables.  Maybe.  But not going to dive into this to make sure.  Let's just agree that v1.4 and v2.0(dev version) aren't compatible and run away.  ;-)

**Comment by lea-hagen** [comment]
Sounds like a good plan!

**Comment by lea-hagen** [comment]
I'm skimming through issues to see if I expect any additional changes for v1.4, and here's what I've come up with:
* merge #501 (skipping already-trimmed files)
* address #466 (merging output files)
* any new analysis code for a catalog paper (#333) that hasn't been written yet

The first one is ready to go (I think), and the latter two should be easy enough to incorporate if/when we need to.

**Comment by karllark** [comment]
@lea-hagen : thanks for the summary.  Sounds great.  I would propose that I merge #501, cherry pick it into the v1.4 branch, and then do the v1.4 release.  Then we can cherry pick any other PRs into the v1.4 branch and release subversions of v1.4 as needed (e.g., v1.4.1).  Sounds like a good plan?

**Comment by lea-hagen** [comment]
That sounds perfect.  Thanks!

**Comment by karllark** [comment]
BEAST v1.4 has been released.

https://github.com/BEAST-Fitting/beast/releases/tag/v1.4.0

**Comment by lea-hagen** [comment]
(Not sure where to add this, but here seems reasonable)

I did identical runs -- phat_small with subgrids -- using v1.4 and v2.0, and the results (stats, 1D PDFs, 2D PDFs) are identical.  The only difference, presumably from how the PDF-generating code loops through parameters, is that some pairs of parameters in 2D PDFs are in a different order.  That won't affect anything, unless a particular field was run partially with one version and partially with another (merging wouldn't work), but I can't imagine such a scenario happening.

Also, in contrast to the comment above, an SED grid generated with v1.4 can be read and used in v2.0.
