### ISSUE TITLE
question about simulation procedure

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#512]
I'm doing some BEAST simulations (remove some filters, see how fits change) and I'm wondering about the proper way to do it.  I see two options:

1. Use an existing BEAST run with all filters.  Remove desired filters from physics model and noise model.  Use them to create simulated data.  Run the BEAST on that simulated data.

2. Use an existing BEAST catalog/ASTs.  Run the BEAST with the whole data set.  Remove desired filters from catalog/ASTs.  Run the BEAST (including creating new physics/noise models) on that new data.

I'm having trouble wrapping my mind around whether 1 or 2 would be better.  With 1, the new catalog is representative of the priors, which may not be fully probed with 2.  But 2 is real observations being run through the whole pipeline, which seems like a closer representation of what would really happen.

**Comment by karllark** [comment]
From our off-line conversations, I think either 1 (modified) or 2 will work.  For 1, I would say do the simulation with the full set of  filters.  Then remove filters and run the BEAST fitting.  That allows one to directly test the impact of different filters for exactly the same set of simulated stars.  Option 2 will do the same thing, but only if you have the real data to begin with.

**Comment by karllark** [comment]
Closing as I think the answer is "it depends."
