### ISSUE TITLE
Run needed for IR LUVIT proposal

### ISSUE THREAD

**Issue by marthaboyer** [BEAST-Fitting/beast#515]
I need a BEAST justification figure for the IR LUVIT proposal.  Last year, I used the attached figure, which I hacked together from old runs. 

![image](https://user-images.githubusercontent.com/22348778/75559165-fa16db80-5a10-11ea-89e4-51ac30ade4d2.png)

This is OK, but what I'd really like is a run that demonstrates how important the IR and F475W are for *evolved stars*.  Since these stars aren't detected in the UV (for the most part), not having the IR means we've only got 2 bands for the BEAST (no bueno).  Plus, we need to justify asking for F475W as opposed to the F606W data that's in the archive.  We could probably demonstrate this using RGB stars since trying it with AGB stars might complicate things due to a lack of circumstellar dust in the BEAST.

As a reminder, the goal of this proposal is to study both the AGB stars and more massive evolved stars (RHeB and BHeB).

**Comment by karllark** [comment]
Can you say what filters we currently have and what filters you are proposing for?

**Comment by marthaboyer** [comment]
We currently have Karrie's UV: F275W & F336W and optical data in the archive: F606W & F814W

I'd add F475W, F110W, and F160W (plus some medium-band IR filters, but we can skip those for this demo, I think).

**Comment by karllark** [comment]
Closing has the proposal has been written *and* accepted!

**Comment by marthaboyer** [comment]
Yay!
