### ISSUE TITLE
Issues with creating catalogs for BEAST verification

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#517]
I'm doing a verification run in which I use a model/noise grids to create a simulated catalog.  That catalog has very few, if any, high-mass stars (which I'm defining as >3 Msun).  I've narrowed it down to two related reasons.

1. Mass prior: The code in `gen_SimObs_from_sedgrid` weights the likelihood of a given SED point by its weight, which is a combination of grid and prior weights.  The prior for mass is the IMF, which means it preferentially selects low-mass stars.  I did a test in which I change it to use just the grid weights, which is a flat mass prior, but I still have the same problem.

2. Age prior: Because the age grid is log-spaced, the grid weighting prefers old ages.  So using the grid weight in `gen_SimObs_from_sedgrid` means picking more low-mass stars (which are still alive).  The prior weight is relatively constant for each age, but if I can't use that without running into the IMF issue.

The one option I've thought of is to ignore the weight info in the SED grid and create my own weights.  Presumably this would just be grid weights for metallicity and mass, since those are the two quantities that could have uneven spacing, and no prior weights.  I haven't done any looking at the grid/prior weight code for the dust parameters, so I'm not sure how this would effect those, particularly Rv/fA, which have a complicated shape.  Perhaps they need some custom weights, too, to make sure that they are fully sampled.

**Comment by karllark** [comment]
You could use the `exp` stellar prior to select for young stars.  The `tau` parameter is in Gyrs.  So picking 0.1 would strongly favor 100 Myr and younger stars.

**Comment by karllark** [comment]
Or the `flat_log` age prior model.  See https://beast.readthedocs.io/en/latest/beast_priors.html#stellar
