### ISSUE TITLE
Tests for stellar grid/prior weights

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#521]
Tests needed for grid and prior weights in 1D (mass, age, metallicity [distance already done).
3D done (mass, age, metallicity) as part of the phat_small regression tests.
4D needed (adding in multiple distances).

**Comment by s-goldman** [comment]
I can try to tackle this one

**Comment by s-goldman** [comment]
@karllark  it looks like there is a simple test for each of them already. You were suggesting something a little bit more that what's there?

**Comment by s-goldman** [comment]
The tests that we currently have are for distance.

**Comment by karllark** [comment]
Are there tests for the 1D for the stellar prior/grid weights?  I can't find them, but that doesn't mean they do not exist.   These would be tests similar to the distance, but for age, mass, metallicity.  If these already exist, can you point me to them.

**Comment by s-goldman** [comment]
No those don't exist, but I can make them

**Comment by karllark** [comment]
Great.

**Comment by s-goldman** [comment]
#533  includes all of the tests for stellar grid weights

**Comment by s-goldman** [comment]
@karllark  All unit tests for stellar grid weights and priors should be complete!
