### ISSUE TITLE
remove_filters.py can't distinguish between instruments

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#527]
Our catalog files only have a short filter name for the column names.  If a model grid has the same filter in two different instruments (e.g., F475W in both ACS and WFC3), neither of them get removed, because the filter name from the catalog file exists in both strings (e.g., `F475W` is in both `HST_ACS_WFC_F475W` and `HST_WFC3_F475W`).

This will also be a problem if the `rm_filters` keyword is set and a filter is in the grid with two instruments.

I know that at various points, we've talked about naming the catalog columns with the filter AND instrument, which would solve this.  Could also probably add an optional input to remove_filters.py that takes instrument names.

**Comment by karllark** [comment]
Should probably move to identifying the observatory, instrument, and filter.  I wouldn't be surprised if HST and JWST have the same filters.  Instrument should identify, but might as well as observatory to make it "clean" and to *never* have this problem again.
