### ISSUE TITLE
Docs: Streamline BEAST Development page

### ISSUE THREAD

**Issue by jwuphysics** [BEAST-Fitting/beast#532]
The BEAST Development page contains duplicate "Development Install" sections as well as an empty "Collaborating and Contributing" section. Moreover, it might be nice to add a "Submit Pull Request" section/blurb, and also a "Keeping up-to-date with upstream master branch" (see #529).

**Comment by jwuphysics** [comment]
I investigated the history of the `docs/beast_development.rst` file and noticed that large amount of text was removed in commit 4f84735. Some of it was re-added (but perhaps not in the correct order) in commit 81833d7.

**Comment by karllark** [comment]
A bunch of the text that was readded in the latter commit should be removed.  The goal of the docs is to give enough info, but not to completely replicate what is standard and available in other places.

**Comment by jwuphysics** [comment]
@karllark I've kept in the text about "Adding Branches" and "Making Changes" but am happy to delete them again if needed.
