### ISSUE TITLE
conda packages out of date

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#548]
In the installation instructions, we run
```
conda install astropy scipy h5py matplotlib cython
```
For reasons unknown to me, the packages it downloads are out of date.  Some examples from a quick check:
* numpy 1.13.1 (most recent is 1.18.3)
* scipy 0.19.1 (most recent is 1.2.3)
* h5py 2.7.0 (most recent is 2.10.0)
* pytest 3.2.1 (most recent is 5.4.1) 

I don't know if it's the conda channel I'm using, or if a bunch of packages don't keep their conda installation up-to-date, or what exactly.  But it means I have to go back and re-install a bunch of things with pip, which might not be a good thing to do.

Is this something we need to change in the installation procedure, or is it just me?

**Comment by karllark** [comment]
This does not sound good.  @eteq - you are the expert on this.  Is this the result of the work you did to better configure conda?

**Comment by lea-hagen** [comment]
Doing `conda install -c anaconda astropy` got me the latest version of astropy (rather than 2.0.1, as it was doing before), as well as the latest numpy.  That makes me think it's an issue with my channels.  For reference, here's what's in my `.condarc` file:
```
channels:
  - http://ssb.stsci.edu/astroconda
  - https://repo.anaconda.com/pkgs/free
  - https://repo.anaconda.com/pkgs/pro
```
I'm definitely not a conda expert, though, so other suggestions are welcomed!

**Comment by lea-hagen** [comment]
I figured out about a week ago that this problem is indeed because of the channels (the last two are deprecated).  So I'll close this.
