### ISSUE TITLE
@remote_data question

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#556]
I've been digging into pytest today, and I have a question.  For the BEAST tests marked as needing remote data (`@remote_data`), it's done via `from astropy.tests.helper import remote_data`.  But looking at that code, it appears to just be equivalent to `import pytest` and then using `@pytest.mark.remote_data` (with the [remote data pytest plugin](https://github.com/astropy/pytest-remotedata)).  Could someone (@karllark? @eteq?) help me understand why we're not using the latter method?  Or does it really matter?

**Comment by karllark** [comment]
I have no idea.  I don't think it matters as we depend on both for our tests.

**Comment by karllark** [comment]
Going to close this due to inaction.  Can be reopened if needed.
