### ISSUE TITLE
idxs referenced in pick_models_toothpick_style before assignment 

### ISSUE THREAD

**Issue by christinawlindberg** [BEAST-Fitting/beast#560]
There doesn't seem to be any code assigning `idxs` for the general case in `make_ast_inpit_list.py` (it gets referenced in `line 159`).

It seems like the original line declaring the `idxs` was removed in the last commit 20 days ago. It originally said `idxs = np.where(modelsedgrid.grid["logL"] > -9)[0] ` on `line 136`.

I don't know why this was deleted though. Any help in fixing this would be much appreciated.

**Comment by galaxyumi** [comment]
This cut has been moved in the generating the Specgrid stage, not in the selecting input ASTs. See #558 and the relevant issues referenced therein.

**Comment by karllark** [comment]
@christinawlindberg : does @lea-hagen's response answer your question?

**Comment by christinawlindberg** [comment]
> @christinawlindberg : does @lea-hagen's response answer your question?

From #558? I can see the discussion but I'm afraid I don't fully understand what's going on. Is there a different function that should be called while generating the input ASTs?

**Comment by karllark** [comment]
The idea is that the models are filtered out when the sed grid is created, so cutting them out again when making the asts inputs is no longer needed.  If you have such models in your sed grid, if you get the latest beast version (either via pip or by fetching upstream and merging) and then remake your sed grid those models will be gone.

**Comment by christinawlindberg** [comment]
So you're trimming the SED grid first thing when creating it?

**Comment by lea-hagen** [comment]
A very tiny fraction of the isochrones we download from the website have luminosities that are unphysically small (#309, #486), so we need to discard them, since they're not actually stars.  They were originally deleted in `make_ast_input_list`, but then we realized it would make more sense to delete them when first generating the model grid.

This is distinct from the trimming step when running the BEAST.  I know it gets confusing when we use the same words to mean different things!

**Comment by christinawlindberg** [comment]
Just for documentation's sake, here's the error I should've included in my original post.

---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
<ipython-input-21-4574335f732e> in <module>
      1 if not os.path.isfile(ast_input_file):
----> 2     make_ast_inputs.make_ast_inputs(flux_bin_method=True)

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/beast/tools/run/make_ast_inputs.py in make_ast_inputs(flux_bin_method)
     78                 outfile=outfile_seds,
     79                 outfile_params=outfile_params,
---> 80                 bins_outfile=bins_outfile,
     81             )
     82 

~/anaconda3/envs/astroconda/lib/python3.6/site-packages/beast/observationmodel/ast/make_ast_input_list.py in pick_models_toothpick_style(sedgrid_fname, filters, Nfilter, N_fluxes, min_N_per_flux, outfile, outfile_params, bins_outfile, bright_cut)
    157     counter = 0
    158     successes = 0
--> 159     include_mask = np.full(idxs.shape, True, dtype=bool)
    160     chunksize = 100000
    161     while True:

UnboundLocalError: local variable 'idxs' referenced before assignment

**Comment by karllark** [comment]
This is definitely a bug.  @galaxyumi : can you look at this problem as you most recently worked on this file?  If you don't have time, tell me and I'll give it a go.

**Comment by karllark** [comment]
Thanks for the additional details @christinawlindberg !

**Comment by galaxyumi** [comment]
I just saw this issue. Yes, this is a bug. I will fix it soon!
