### ISSUE TITLE
Change default `max_nbins` for PDFs?

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#570]
I just (re-)noticed that there's a parameter in `Q_all_memory` (beast/fitting/fit.py), `max_nbins`, that sets the maximum number of bins for the 1D and 2D PDFs.  The current default is 50.  So even if the grid is more finely sampled, the PDFs will have at most 50 bins.  Does this default still make sense, or should it be increased for production runs?  I'm unsure if the coarser PDF resolution will impact science goals.  Currently, their only use is for doing cuts for star types.

**Comment by karllark** [comment]
Making this larger is not a problem in my mind.  When I set it originally, it was picked as being a reasonable number.  Higher numbers would be quite possible.  Do you have a suggestion?  Are we hitting the 50 max with your current grids/runs?

**Comment by lea-hagen** [comment]
The parameter for which this would be most relevant is A_V (goes from 0 to 10 in steps of 0.05, for 200 grid points).  Also would impact non-gridded quantities like mass, radius, temperature, etc.  The main impact would be larger file sizes, but I'm not sure off the top of my head how much larger.

Also, I noticed that the parameter percentiles are calculated using the 1D PDFs (`_p` is the list of percentiles to calculate, e.g., `[16, 50, 84]`).  I don't \*think\* this would be impacted by changing the binning, but I'm not 100% sure.
https://github.com/BEAST-Fitting/beast/blob/f3abaf346107034d5aede94e313a471c5409c78d/beast/fitting/fit.py#L727

**Comment by karllark** [comment]
> Also, I noticed that the parameter percentiles are calculated using the 1D PDFs (`_p` is the list of percentiles to calculate, e.g., `[16, 50, 84]`). I don't *think* this would be impacted by changing the binning, but I'm not 100% sure.

Probably not.  The calculation is done by interpolation of the cumulative summed pdf (if my memory is correct), so it won't change much if at all.

**Comment by lea-hagen** [comment]
I did a simple test to visualize what happens with changing bin widths.  I copied the code below for reference, but what I did was generate a bunch of AVs by randomly grabbing from the grid (0 to 10, steps of 0.05), assuming a normal distribution centered at 0.51 and a standard deviation of 0.1.  To simulate 1D PDFs, I made histograms with different bin widths, and then used those to estimate the percentiles.  Here's a plot of the histograms:
<img width="564" alt="Screen Shot 2020-06-01 at 12 32 43 PM" src="https://user-images.githubusercontent.com/32465297/83430690-18bbb280-a404-11ea-86ac-ff164ceba814.png">
And here are the expected and calculated results:
```
actual percentiles: [0.4 0.5 0.6]
desired result: [0.41, 0.51, 0.61]
percentiles for n_bins=20: [0.25       0.5725     1.00193798]
percentiles for n_bins=50: [0.3671159  0.54038877 0.68725702]
percentiles for n_bins=100: [0.41927536 0.53554396 0.64636364]
percentiles for n_bins=200: [0.43679577 0.53533592 0.63876147]
```
What I conclude is that the number of bins does change the result, especially when the binning is very coarse.  For AV, the grid has 201 points, and we're currently using 50 bins.  I'd advocate increasing the max to 100, unless the gains going up to 200 seem worth the additional file size increase.
-----
```
import numpy as np
from beast.fitting.fit_metrics.common import percentile
import matplotlib.pyplot as plt
from matplotlib import cm
import scipy

def test_percentile():
    """
    test how binning effects the percentiles
    """

    av = np.linspace(0, 10, 201) # 0 to 10 in steps of 0.05
    mean = 0.51
    stdev = 0.1
    av_prob = scipy.stats.norm(loc=mean, scale=stdev).pdf(av)
    av_prob /= np.sum(av_prob)
    data = np.random.choice(av, 1000, replace=True, p=av_prob)

    p = [16, 50, 84]

    print('actual percentiles:', np.percentile(data, p))
    print('desired result:', [mean-stdev, mean, mean+stdev])

    cmap = cm.get_cmap('plasma_r')

    bins = [20, 50, 100, 200]

    for i,n_bins in enumerate(bins):

        # bin edges/centers
        bin_edges = np.linspace(np.min(av), np.max(av), num=n_bins+1)
        bin_centers = (bin_edges[1:] + bin_edges[:-1])/2

        # create PDF
        pdf, edges = np.histogram(data, bins=bin_edges, density=True)

        # plot PDF
        plt.hist(
            data, bins=n_bins, range=(np.min(av), np.max(av)), density=True,
            histtype='step', linewidth=1.3*len(bins)-1.3*i, alpha=0.7*i/len(bins)+0.3,
            label=str(n_bins)+' bins', color=cmap(0.9*i/len(bins)+0.1)
        )
        plt.xlim(0,1.2)

        # calculate percentiles
        print(
            'percentiles for n_bins='+str(n_bins)+':',
            percentile(bin_centers, p, weights=pdf)
        )

    plt.legend()

if __name__ == '__main__':
    test_percentile()
```
