### ISSUE TITLE
undefined variable in run_fitting.py

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#572]
After merging PR #571 into v1.4, I went to merge this change into v2.0 and had a minor conflict.  In fixing this conflict, I found that the variable `pdf_max_nbins` was undefined in two places in `run_fitting.py` (lines 289 and 311).  This was found by the standard `flake8` linter that is run automatically when I use atom (`linter` and `linter-flake8` atom packages).  This error was not revealed in the travis testing as the issue is in the `fit_submodel` function. 

Needs fixing I believe.

**Comment by lea-hagen** [comment]
Ah, I found the problem.  I'll do another PR.
