### ISSUE TITLE
Incorrect datamodel import

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#576]
After #573, `datamodel` no longer imports correctly.  It imports the new stubs rather than importing the local user-defined `datamodel.py`.  Here's the error for phat_small:

```
In [1]: %run run_beast.py -potf
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/astro/dust_kg3/lhagen/stsci/beast-examples_lea-hagen/phat_small/run_beast.py in <module>
     65     if args.physicsmodel:
     66
---> 67         create_physicsmodel.create_physicsmodel(nsubs=1, nprocs=1)
     68
     69     if args.ast:

/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/tools/run/create_physicsmodel.py in create_physicsmodel(nsubs, nprocs, subset)
     57     importlib.reload(datamodel)
     58     # check input parameters
---> 59     verify_params.verify_input_format(datamodel)
     60
     61     # filename for the SED grid

/astro/dust_kg3/lhagen/stsci/beast_lea-hagen/beast/tools/verify_params.py in verify_input_format(datamodel)
    120
    121     parameters = [
--> 122         datamodel.z,
    123         datamodel.obsfile,
    124         datamodel.astfile,

AttributeError: module 'beast.tools.run.datamodel' has no attribute 'z'
```

**Comment by karllark** [comment]
Blarg.  Not quite sure how to solve this as we are importing a module called `datamodel` and if it doesn't exist, then we get test errors.  The real answer is to stop importing this and got to a different solution.  Now that all the of the functions/classes have been removed from datamodel.py, can we just read in the datamodel.py file with your other method?

**Comment by karllark** [comment]
Reading over PR #326 - I wonder if the revised datamodel.py could just be renamed(?) and read in as that PR already does?

**Comment by lea-hagen** [comment]
I just looked back over at #326, and it's more complete than I remembered!  So yes, I think it wouldn't be too difficult to finish implementing it, which would solve this.

**Comment by karllark** [comment]
Awesome.  Will you have time before the next BEAST HackDay to do this?  Or is it a BEAST HackDay project?

**Comment by lea-hagen** [comment]
Good question.  I'll start on it and see how it goes!

**Comment by lea-hagen** [comment]
Actually, I think I'll try to do it pre-hack day, since it would be sub-optimal to start a hack day with the BEAST unable to run.

**Comment by karllark** [comment]
That would be awesome.  I want to update the package files and switch to github actions for CI testing.  Get things working smoothly before hacking!

**Comment by karllark** [comment]
So, I will be doing a PR myself in the next few days.  Shouldn't impact your work as all the files I'll be messing with are package stuff, not actual BEAST code.
