### ISSUE TITLE
Streamline BEAST settings as a class?

### ISSUE THREAD

**Issue by cmurray-astro** [BEAST-Fitting/beast#587]
Rather than updating the datamodel.py file (or new BEAST settings file) locally, it would be great to implement a class so that variables can be updated in the workflow/code. Not sure if this is already happening (@lea-hagen)?

**Comment by lea-hagen** [comment]
Yes, this is covered in #579!

**Comment by karllark** [comment]
One thought here is that if we treat it as a class, then it could/should be read in only once and then the class variables updated where needed.  This would be instead of writing a new settings file and re-reading it in.
