### ISSUE TITLE
MATCH/BEAST Test parameter space

### ISSUE THREAD

**Issue by cdb201** [BEAST-Fitting/beast#590]
(https://docs.google.com/spreadsheets/d/1D9ulDJrNUgnSG-X4cxeeS8NWGEC80STPUvPuIiQGgKk/edit?usp=sharing) 

This link will get you to the scylla parameter space. There is a key at the bottom to understand what each of the symbols mean. The two tables have the same information, just written in two different ways. 

*NOTEBOOK 2 is where the data is housed

**Comment by karllark** [comment]
I think this issue can be closed as it has been discussed in the appropriate telecon.  Please reopen if this is not the case.
