### ISSUE TITLE
Units needed for derived luminosity measurements

### ISSUE THREAD

**Issue by christinawlindberg** [BEAST-Fitting/beast#606]
There currently isn't any info about what units the derived stellar luminosity is for any of the PHAT results (which I'm assuming applies to all BEAST results). The info file just says 

`logL = log10 of the stellar luminosity`

**Comment by karllark** [comment]
Should be straightforward to answer by examining the physics grid creating where this quantity is calculated.  Probably in creategrid.py.

**Comment by christinawlindberg** [comment]
Found in stellib.py 
`logL  log of luminosity in Lsun units`

which I'm assuming means solar luminosity? 
Also, the temperature is in Kelvin if there was ever any doubt.

**Comment by karllark** [comment]
Yep.  Lsun = solar luminosity.
Would be great if you wanted to do a PR to add this info to the docs!

**Comment by christinawlindberg** [comment]
Would surface gravity also be in solar gravity units?

**Comment by karllark** [comment]
log(g) is expressed as log10(cm s^-2).  Real astronomer units!

**Comment by christinawlindberg** [comment]
Thanks! I'll add that to the documentation as well.
