### ISSUE TITLE
Question about saving log likelihoods (with subgrids)

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#619]
I have a question about the sparsely sampled log likelihoods.  For production runs, I'm saving 500 for each fitting run.  But that's multiplied by however many subgrids (10 in my case) that get merged, so really it's 5000.  Do we want to keep all 5000, or somehow pare it down to 500?  If the latter, pick the 500 highest likelihood, or randomly select?  

I'll also add that in the merging step, there's a cut that discards any lnPs that are more than 10 away from the minimum lnP (e.g., if the min lnP is 100, any lnPs greater than 110 are discarded).  During the fitting, this same cut is made before randomly choosing the lnPs to save.

**Comment by karllark** [comment]
If space is not a problem, I would keep all the lnp values that pass the threshold.

**Comment by lea-hagen** [comment]
Really depends on what amount of space you would consider to be a problem 😆.  Current rate is ~100 MB for 1000 stars.

**Comment by karllark** [comment]
So, is that a problem?

**Comment by karllark** [comment]
I think this question has been answered.  I'm going to close the issue, please re-open if this is not the case.
