### ISSUE TITLE
best chi^2 doesn't match best Pmax

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#622]
While puzzling over #621, I stumbled across a discrepancy in the best chi^2 and the best Pmax.  Here are the two columns in the stats file for metal_small:
```
<Table length=500>
chi2min_indx Pmax_indx
   int64       int64
------------ ---------
      123755    137772
       19246     21272
         232       351
      180733    151852
       41173     40785
         105     65811
        1773      1369
       21666     29100
         201       201
         ...       ...
       64571     64750
        1608     19413
       65496       351
       42231     23031
        1642      1642
       60219     60219
       39440     39143
         237       355
      158438    141283
       61384     61384
```
Presumably, the SED that corresponds to the lowest chi^2 should be the same SED as the highest log likelihood.  But in metal_small, they only match in 105/500 stars.

**Comment by karllark** [comment]
The chi2 max can be different than the Pmax.  The chi2 is the straightforward, as expected, chi2.  The Pmax includes the prior as well.  Hence, they can be different.  At least that is my memory, would have to check the code to confirm.

**Comment by lea-hagen** [comment]
After some more investigating in `fit.py`, I think I may have tracked it down.  The `lnp` values get multiplied by the prior weights before finding the largest value.  The chi^2 values aren't modified, so as far as I can tell, they don't have the priors incorporated.  So does that make the `chi2min` and `chi2min_indx` irrelevant?

**Comment by lea-hagen** [comment]
Haha, figured it out at the same time!

**Comment by karllark** [comment]
Not necessarily.  It might be interesting to see what fits best as opposed to what is the most probability including the priors.

**Comment by lea-hagen** [comment]
Ah, that makes sense.  Thanks!
