### ISSUE TITLE
BEAST graphic - useful for docs?

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#623]
As a follow on of @eteq's great tutorial this morning, I've attempted to create a graphical model for the BEAST.  This is just the 1st cut at doing this.  I wonder if this would be useful to add to the docs?  Comments?  Questions?  Suggestions for improvements?

Both have been updated based on comments given below.  See PR #624 for notebook that creates these figures.

Here is the version using understandable words.

![beast-graphic](https://user-images.githubusercontent.com/1554536/93820977-ec82a680-fc2b-11ea-812c-6bf5af117eb6.png)

Here is the version using symbols based on the equations in the BEAST paper.

![beast-graphic-symbols](https://user-images.githubusercontent.com/1554536/93821005-f3a9b480-fc2b-11ea-8d9b-c3fc5a1ffcd2.png)

**Comment by galaxyumi** [comment]
Great! I think it's helpful to understand the BEAST flow. One minor comment is that ASTs is not completely independent in the BEAST cause the input artificial stars are selected from the model grid. I think it would be great if you can make that connection in this graph.

**Comment by karllark** [comment]
Good point @galaxyumi!  I'll update the files above.

**Comment by jwuphysics** [comment]
I think this is really neat. It summarizes the different things that go in (model assumptions, physics, observables, etc) at a glance. Actually, this would have been really helpful when I first started contributing to the BEAST!
