### ISSUE TITLE
BEAST Input ASTs Not Populating Source Density Bins

### ISSUE THREAD

**Issue by christinawlindberg** [BEAST-Fitting/beast#626]
We currently have ways to check if the AST inputs being generated by the BEAST are sampling the entire magnitude range we want, but I don't believe we have been checking whether the source density bins have been populated as well.

For Scylla field SMC_6 (15891_SMC-3956ne-9632), I find that when I convert the (X,Y) coordinates to (RA,DEC) and run them through `split_catalog_using_map.split_main()`, I see that some of the source density bins only have a couple dozen input ASTs generated for them. 

![image](https://user-images.githubusercontent.com/24800168/94487939-c3c05b00-01af-11eb-8f60-2698417bfcfb.png)

I've plotted the number of sources and the number of ASTs generated for each source density bin above. Note that SD 11 and 17 are empty since there weren't any sources with that source density.

The concerning bin is bin 10, which only had 22 sources and only had 40 ASTs generated for it.

![image](https://user-images.githubusercontent.com/24800168/94488236-3c271c00-01b0-11eb-99e6-c2fed1397b6c.png)

I also plotted the number of AST inputs generated per source. Interestingly enough, the ratio was a lot higher for bin 10. I'm unsure if this is actually of any use knowing. 

From my understanding, I thought that the BEAST randomly generated ASTs from the physics model until every magnitude had _at least_ some _n_ predetermined number of ASTs. I'm not sure if the same requirement is set for ensuring that all the source density bins are filled as well. I would have expected that there's something checking that the source density bins are being filled as well, but if they're just being placed randomly within the reference image provided, then it would make sense that if there's only one small square that has a source density of 10, then the number of ASTs placed within that square should be proportional to the size of that square divided by the total area (aka, tiny). 

If there are any developers on here (@lea-hagen @karllark ) that can speak to whether my train of thought is correct or not, I'd greatly appreciate it. If you want a copy of the files I'm using to generate these results, I'll happily add those as well.

![image](https://user-images.githubusercontent.com/24800168/94489252-1c90f300-01b2-11eb-862d-d53421647774.png)
(and here's a list of all the splitting numbers since I plotted stuff on a log scale earlier)

**Comment by christinawlindberg** [comment]
A secondary question I had was, why doesn't the ast_input list include the RA and DEC measurements as well (or the source density value base on position, if that's being generated)?

**Comment by karllark** [comment]
Solve in PR #643.
