### ISSUE TITLE
Unclosed noisemodel files

### ISSUE THREAD

**Issue by lcjohnso** [BEAST-Fitting/beast#64]
When running phat_small example, the following files are left unclosed:
beast_example_phat/beast_example_phat_noisemodel.hd5
beast_example_phat/beast_example_phat_noisemodel_trim.grid.hd5

Is there a missing close statement somewhere?

**Comment by karllark** [comment]
That is how the file is called/used.  See line 118 of beast/observationmodel/noisemodel/generic_noisemodel.

**Comment by lea-hagen** [comment]
Here's the relevant function in `generic_noisemodel.py`:
```
def get_noisemodelcat(filename):
    """
    returns the noise model

    Parameters
    ----------
    filename: str
        file containing the outputs from OneD_ASTs_ModelGenerator

    Returns
    -------
    table: pytables.Table
        table containing the elements of the noise model
    """
    return tables.open_file(filename)
```
The object it returns would have to be closed somewhere in whatever code calls this function.

**Comment by karllark** [comment]
Should update the gen_noisemodelcat function to only return the table.  Maybe.  Will need to check how this is being used in those 12 files.

**Comment by karllark** [comment]
At least in places, specifically accessing the info in the noisemodel file via hdf5 commands.  Definitely should replace this with an astropy table to start making this less specific and working on our technical debt.
