### ISSUE TITLE
Why is N_bins used to re-bin the input map for placing ASTs?

### ISSUE THREAD

**Issue by cmurray-astro** [BEAST-Fitting/beast#641]
@lea-hagen on Aug 29, 2018 you added code to make_ast_xy_list.py: 

    bdm = density_map.BinnedDensityMap.create(input_map, N_bins)
    tile_vals = bdm.tile_vals()
    max_val = np.amax(tile_vals)
    min_val = np.amin(tile_vals)
    tiles_foreach_bin = bdm.tiles_foreach_bin()

This appears to re-bin the input source density map into "N_bins" (parameter settable in beast_settings), so that ASTs are repeated over only these N_bins. We've found that this ends up way under-sampling the highest source density bins in Scylla fields (as we thought that ASTs were replicated across *all* SD bins, instead of, in this case the setting in the template file is "4"). Was there a reason for this change / why would you only want to replicate ASTs across fewer SD bins than you have in the image?

**Comment by karllark** [comment]
Fixed in #643.
