### ISSUE TITLE
changes to pick_positions in make_ast_xy_list

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#653]
In #634, I changed the inputs to `pick_positions` so that the input SED file wouldn't get overwritten (instead, it made a new output file, just as `pick_positions_from_map` does).  It looks like that got reverted in #643, and I can't figure out why - the commit message mentions bug fixes for source density binning that are unrelated.  My guess is that it was an accidental change, but I want to make sure I didn't miss something while I was away!

@cmurray-astro

**Comment by lea-hagen** [comment]
I just noticed that the call to `pick_positions` in `tools/run/make_ast_inputs.py` still has the changes from #634, so definitely an accidental change 😄

**Comment by cmurray-astro** [comment]
Yea I can't tell why that change was in #643! Sorry about that, must have been accidental.

**Comment by lea-hagen** [comment]
No worries!  I'm working on it now - will probably take 3 minutes :)
