### ISSUE TITLE
'simulate_obs' might underestimate errors/biases. 

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#660]
After simulating ASTs based on the real ASTs, I computed their completeness as a function of color and magnitude. The 50% completeness values turned out to be more than 1 magnitude fainter than those computed from the real ASTs for my test case. It might indicate that we are underestimating errors/biases.

For the real ASTs, explicit cuts are made on S/N, sharpness, crowding, and mag_out-mag_in. For the simulated ASTs, the combined effect of S/N, sharpness, and crowding is expected to be correctly captured in the recovered photometry. These needs to be double checked.

**Comment by karllark** [comment]
Definitely!  This could be a bug in the simulation code or the observation model or in our collective understanding of the simulations or a combination.

**Comment by galaxyumi** [comment]
While talking to @k-gilbert about this, we suspect that using fluxes (including negative fluxes) in the BEAST somehow cause this issue.

**Comment by karllark** [comment]
Can you be more specific in how fluxes is causing this issue?

**Comment by galaxyumi** [comment]
It's a bit tricky for me to specify my doubts about fluxes b/c I don't understand all the details about constructing a noisemodel grid from real ASTs. But let me try. To me, it's unclear how the S/N cut can be reflected when all the fluxes are used when constructing a noisemodel grid whereas crowding (probably sharpness as well) can be well captured in the bias term.

**Comment by karllark** [comment]
I think we need to have a video chat to discuss this issue.  I also do not fully understand how the S/N cut is being used - I suspect it is not.  I need to better understand how the cuts are done.

**Comment by karllark** [comment]
Need to apply a 0.75 mag cut in input - output mag for ASTs to remove the erroneous recovered sources.   This should (to first order) cleanup the the observation model and fix the simulated ASTs.  To be tested!

**Comment by karllark** [comment]
This should have been fixed with PR #678.  @galaxyumi when you get a chance, can you test if this is the case?  If this hasn't bee fixed, please reopen this issue.

**Comment by galaxyumi** [comment]
> This should have been fixed with PR #678. @galaxyumi when you get a chance, can you test if this is the case? If this hasn't bee fixed, please reopen this issue.

Great! I will do.
