### ISSUE TITLE
problem with tox test coverage

### ISSUE THREAD

**Issue by lea-hagen** [BEAST-Fitting/beast#665]
The current [test docs](https://beast.readthedocs.io/en/latest/beast_development.html#test-changes) say to run
```
tox -e test -- --remote-data --coverage
```
which gives me this error:
```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --coverage
```
If I remember correctly, everything after the `--` gets fed to pytest, and apparently `coverage` isn't something pytest likes.  I have `pytest-astropy` installed, so I don't think that's the issue.  Removing `--coverage` allowed the tests to run, but of course it would also be nice to have the coverage info!

**Comment by karllark** [comment]
There is a way to do this as the github actions do run the coverage.  Maybe check in the gh file for the right syntax?  Maybe this is a documentation issue?

**Comment by lea-hagen** [comment]
Good call!  I think I found it here, but I'm not quite sure which part is the thing to put in the command line call.
https://github.com/BEAST-Fitting/beast/blob/ac10317114846f0bde4be58c66d6e12b260b93dd/.github/workflows/tox-tests.yml#L86-L114

**Comment by karllark** [comment]
The line that starts with `tox` right after the `run: |` line.

**Comment by karllark** [comment]
Going to close this issue.  Please reopen if the answer is not sufficient.  ;-)
