### ISSUE TITLE
Resuming fitting run results in error

### ISSUE THREAD

**Issue by petiay** [BEAST-Fitting/beast#666]
Using the `resume` option in [run_fitting.py](https://github.com/BEAST-Fitting/beast/blob/master/beast/tools/run/run_fitting.py) to restart an interrupted fitting run gives the following `astropy` tables error:

`AstropyUserWarning: hdu= was not specified but multiple tables are present, reading in first available table (hdu=1)`

Perhaps the hdu argument needs to be supplied when reading in the existing table data. See [this astropy documentation](https://docs.astropy.org/en/stable/io/unified.html).

Tracing the error for reference:
```
~/beast/tools/run/run_fitting.py in run_fitting(...)
--> 208     parallel_wrapper(fit_submodel, input_list, nprocs=nprocs)

~/beast/tools/run/helper_functions.py in parallel_wrapper(...)
---> 61             r = function(*a)

~/beast/tools/run/run_fitting.py in fit_submodel(...)
--> 320         fit.summary_table_memory(

~/beast/fitting/fit.py in summary_table_memory(...)
-> 1003     Q_all_memory(

~/beast/fitting/fit.py in Q_all_memory(...)
--> 567         stats_table = Table.read(stats_outname)

~/miniconda3/lib/python3.8/site-packages/astropy/table/connect.py in __call__(...)
---> 60         out = registry.read(cls, *args, **kwargs)

~/miniconda3/lib/python3.8/site-packages/astropy/io/registry.py in read(...)
--> 520         data = reader(*args, **kwargs)

~/miniconda3/lib/python3.8/site-packages/astropy/io/fits/connect.py in read_table_fits(...)
--> 230             return read_table_fits(hdulist, hdu=hdu,

~/miniconda3/lib/python3.8/site-packages/astropy/io/fits/connect.py in read_table_fits(...)
--> 183                 warnings.warn("hdu= was not specified but multiple tables"

AstropyUserWarning: hdu= was not specified but multiple tables are present, reading in first available table (hdu=1)
```

**Comment by karllark** [comment]
Yes.  There was a change to the format of the file to add a 2nd extension with the filter information - useful for plot_indiv_fit.  See PR #605.  

Does the resume code work with these messages?  Or crash?

I'm guessing that adding hdu=1 to the reading of the stats file will fix this issue.

**Comment by petiay** [comment]
Exactly - setting hdu=1 fixes the bug.
