### ISSUE TITLE
pixsize_degrees.value throws a float attribute error

### ISSUE THREAD

**Issue by petiay** [BEAST-Fitting/beast#686]
The call to [create_background_density_map.calc_nx_ny_from_pixsize()](https://github.com/BEAST-Fitting/beast/blob/master/beast/tools/create_background_density_map.py) from [megabeast/tools/make_naive_maps.py](https://github.com/BEAST-Fitting/megabeast/blob/master/megabeast/tools/make_naive_maps.py) gives the following error:

```
megabeast/tools/make_naive_maps.py in create_naive_maps(stats_filename, pix_size)
---> 51     n_x, n_y, ra_delt, dec_delt = calc_nx_ny_from_pixsize(cat, pixsize_degrees)
beast/tools/create_background_density_map.py in calc_nx_ny_from_pixsize(cat, pixsize_degrees)
--> 619     dec_delt = pixsize_degrees.value
AttributeError: 'float' object has no attribute 'value'
```

Commenting out `.value` in `pixsize_degrees.value` fixes the issue, or at least does not produce an error.
(the pix_size value option was not used in the call to the megabeast function, therefore the default was used)

**Comment by karllark** [comment]
Shouldn't this issue be on the megabeast repository (not here on the beast repository)?  If so, please move this issue to there and close it here.

**Comment by petiay** [comment]
The fundamental bug seems to be coming from the BEAST repository, even if I run into it with a call of the megabeast. But I'm up for doing whatever the standard is in such an interdependent situation.

**Comment by karllark** [comment]
Ah.  Ok.  Then it belongs here then.
