### ISSUE TITLE
Current way of using a source density map can cause a problem

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#693]
Currently, a source density map is computed at the very beginning of the BEAST runs without any convex hall or/and erosion conditions are applied. While helping @kmcquinn and her student Max Newman, I noticed that the highest source density bin was outside their eroded convex hall area, resulting in that their input ASTs were selected in a lower number of source density bins than they set in the beast_settings.txt. 

Thus, we need to either create a source density map after applying the convex hull or/and erosion conditions or to apply the conditions to the pre-generated source density map before computing the source density bins.

**Comment by galaxyumi** [comment]
I encountered the same issue for one of my galaxies. I set the number of source density to be 8 in the beast_settings.txt file, but the two lowest and two highest density bins were outside the convex hull where I don't have a full filter coverage. Thus the input ASTs were only populated into four (out of 8) source density bins, resulting in a lower resolution in the noise models eventually.

**Comment by karllark** [comment]
As you say, this sounds like the convex hull and/or erosion conditions need to be moved to the initial source density map creation.  Is this straightforward?  Do we use the same code?

**Comment by galaxyumi** [comment]
I don't see any problems with using the same code, at least the core part. I believe it should be straightforward, but might require some minor modifications. Need to find some time to work on this.

**Comment by karllark** [comment]
Great to hear.

**Comment by cmurray-astro** [comment]
I'll work on this today! My thought is that it would be better(?)/easier to go with Yumi's latter suggestion from her first post -- apply the same erosion conditions to the full/original SD map before computing the SD bins rather than use the erosion conditions to generate the SD map (because this erosion business is only used in pick_positions_from_map). What do you think, @galaxyumi?
