### ISSUE TITLE
SFR=0 bins in the age_prior_model

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#697]
I have a SFH solution for a galaxy, which has zero SFR for some time bins. To simulate multi-band photometry based on this SFH solution, I simply copied all the time bins and corresponding SFRs, including the time bins with a zero SFR, into the age_prior_model parameter in the beast_settings.txt. 

When I executed the following command "beast simulate_obs seds.grid.hd5 noisemodel.grid.hd5 synthetic_phot.fits --compl_filter=F475W --beastinfo_list beast_info.asdf", I got the following error message. The SFR=0 bins might cause zeros (or nan values) in the combined prior and grid weights.

Completeness from HST_ACS_WFC_F475W
/Users/ychoi/Research/beast/beast/observationmodel/observations.py:379: RuntimeWarning: invalid value encountered in true_divide
 curweights /= np.sum(curweights)
Traceback (most recent call last):
 File “/Users/ychoi/anaconda3/bin/beast”, line 33, in <module>
  sys.exit(load_entry_point(‘beast’, ‘console_scripts’, ‘beast’)())
 File “/Users/ychoi/Research/beast/beast/main.py”, line 90, in main
  func(**funcargs)
 File “/Users/ychoi/Research/beast/beast/tools/simulate_obs.py”, line 121, in simulate_obs
  ranseed=ranseed,
 File “/Users/ychoi/Research/beast/beast/observationmodel/observations.py”, line 381, in gen_SimObs_from_sedgrid
  model_indx[gmods], size=nsim_curage, p=curweights
 File “_generator.pyx”, line 644, in numpy.random._generator.Generator.choice
ValueError: probabilities contain NaN

**Comment by galaxyumi** [comment]
Having SFR=0 bins was not an actual problem. The problem was that the min and max values of my specgrid["logA"] were slightly (by a few 0.001) outside the min and max values of my age_prior_model["logages"]. This restriction should be documented probably in the simulating observations section. In general, more detailed information about how to generate simulations based on a given SFH might be extremely helpful.

**Comment by karllark** [comment]
Would there be a way to add a check for this and issue an error if found?  Even better than documentation.

**Comment by galaxyumi** [comment]
A fix for this issue has been included in PR #699
