### ISSUE TITLE
Docs: Expectations on input files

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#701]
Detail the expectations the BEAST has on input files. 

At least the following (add more to as a comment to this issue):

observed catalog: all sources have *flux* measurements in all bands (no upper limits).  Negative fluxes allowed

ast results: all sources have input mags and output fluxes in all bands.  Negative fluxes allowed.

observed catalog and ast files should be matched in the number bands.  Selection function.

**Comment by karllark** [comment]
Include pointers to published papers (Scylla, LUVIT) that illustrate this.

**Comment by karllark** [comment]
Maybe add a check for flux=0 data?  Warning to user?

**Comment by cmurray-astro** [comment]
Expects a flag in the output AST file ("CUT_FLAG") which indicates whether or not a source has been cut

**Comment by karllark** [comment]
Similar to #672.
