### ISSUE TITLE
Documentation for setting up datamodel.py

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#71]
Documentation for how to setup datamodel.py for running the BEAST is needed.  Example is useful, but more information in documentation form would be best.

**Comment by lcjohnso** [comment]
Added initial documentation via PR https://github.com/BEAST-Fitting/beast/pull/124, but this could be expanded.

Anyone (especially new users) have suggestions for valuable / helpful items to add?

**Comment by karllark** [comment]
Need to do a thorough review and see if we have enough docs on this topic now.

**Comment by karllark** [comment]
Closing this issue.  We have what we have.  In the new work for v2.0, we'll have to update and that will be the chance to make sure we've got enough.
