### ISSUE TITLE
Duplicate Entries in BEAST

### ISSUE THREAD

**Issue by christinawlindberg** [BEAST-Fitting/beast#716]
I had been working with some of the BEAST stats files (specifically `b02_sd10-11_sub0_stats.fits` from M31 and I noticed there might be duplicate entries with the exact same RA and DEC but different fields. I'm not sure whether these are distinct stars, or if they were somehow duplicated in the pipeline and fit twice.

<img width="631" alt="duplicates" src="https://user-images.githubusercontent.com/24800168/118860837-d7891080-b8a9-11eb-80ce-453b1c27f04d.png">

**Comment by karllark** [comment]
Thanks for opening this issue.  Looking at the entries you give, it looks like they are duplicates in name only.  The RA&DEC values are *slightly* different.  This tells me that the generation of the name does not have enough precision - i.e., we need to increase the number of digits after the decimal in the creation of the name.
