### ISSUE TITLE
fit.py tries to access non-existing files upon resuming fitting step

### ISSUE THREAD

**Issue by petiay** [BEAST-Fitting/beast#722]
**Problem**: An error can result if one tries to resume a stopped fitting run where [fit.py](https://github.com/BEAST-Fitting/beast/blob/master/beast/fitting/fit.py) assumes files may already have been generated when in reality they may not yet exist. Below is an example of the error message.

**Reason**: This happens because [run_fitting.py](https://github.com/BEAST-Fitting/beast/blob/master/beast/tools/run/run_fitting.py) passes on to fit.py a dictionary of filenames (pdf1d_files, pdf2d_files, etc.) which in theory are only generated as filenames by beast/tools/run/create_filenames, but may not have been recorded as actual files.

**Potential solution**: A fix may be for run_fitting.py, around [this line](https://github.com/BEAST-Fitting/beast/blob/42992dd0f5e2e6698fe978aefd800b21516581b7/beast/tools/run/run_fitting.py#L106), to try to grab these files, and if they do not exist, to set their names as None instead of passing on actual file names to fit.py.

@karllark, @christinawlindberg, @galaxyumi, @drvdputt, thoughts?
(seems right now @christinawlindberg and I have both run into this)

```
~/beast-science/beast/fitting/fit.py in Q_all_memory(prev_result, obs, sedgrid, obsmodel, qnames_in, p, gridbackend, max_nbins, stats_outname, pdf1d_outname, pdf2d_outname, pdf2d_param_list, grid_info_dict, lnp_outname, lnp_npts, save_every_npts, threshold, resume, use_full_cov_matrix, do_not_normalize)
    591         if pdf1d_outname is not None:
    592             print("restoring the already computed 1D PDFs from " + pdf1d_outname)
--> 593             with fits.open(pdf1d_outname) as hdulist:
    594                 for k in range(len(qnames)):
    595                     save_pdf1d_vals[k] = hdulist[k + 1].data
FileNotFoundError: [Errno 2] No such file or directory: 'SMIDGE-COMBO-v2_7.cut/SMIDGE-COMBO-v2_7.cut_bin1_sub0_pdf1d.fits'

```

**Comment by christinawlindberg** [comment]
I don't know if that would necessarily solve the issue since these filenames are just assuming what the files will be called in the future. I think the issue might be with the mechanism that detects whether a subfile needs to be run or not, which I'm not quite sure how works. @cmurray-astro @galaxyumi Do either of you know at what point the BEAST decides to run/resume the fitting step in the XSEDE workflow?

**Comment by christinawlindberg** [comment]
I tried running the fitting step again with the suggested fix (changing the missing file names to None if not detected) and I saw no changes in any of my files, which to me indicates that the fitting step needs the specified file names to run.

**Comment by karllark** [comment]
Is this issue still active?  Or should it be closed?

**Comment by petiay** [comment]
I haven't encountered the issue again and it is not clear that I identified the cause properly initially. I'd say we can close it for now. I will do this.
