### ISSUE TITLE
Use of SED grid 'keep' column?

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#73]
The SED grid has 'keep' column.  Is this column used anywhere?  It has changed as revealed by the regress_check code.  Cannot find where it is used.  If not used, should we delete?  If not used, should it be?

**Comment by karllark** [comment]
Working on regression testing, I investigated this a bit more.  It is used internally in gen_spectral_grid_from_stellib in the creategrid.py file.  This is a deprecated function.   Regardless, I've added a line in this function to delete the column once it has been used internally.

I have removed creating this column in the init function in stelllib.  When created, it is empty.  This explains why it would show changes in the regression tests.  It was not initialized so was filled with random True/False values.

These two changes should mean that the keep column no longer appears in the spectral grid file.  This removes the h5py incompatible datatype.

**Comment by galaxyumi** [comment]
Great!

**Comment by karllark** [comment]
Keep column will be removed in pull request #140.

**Comment by karllark** [comment]
Done!
