### ISSUE TITLE
Edge tiles on SD map don't deserve to exist

### ISSUE THREAD

**Issue by christinawlindberg** [BEAST-Fitting/beast#740]
Based on recent XSEDE experiences, it seems that there are occasions where high SD bins (>2) are populated with only a handful of stars (<5 sources). This to me indicates that we are still having issues with source density bins being abnormally high near the edge of our fields like we saw in issue #703 and as visualized in the following source density maps.

These high SD bins are likely barely populated but end up generating lots of extra ASTs. for no good reason. I suggest we increase the frac_area coverage to at least 20%, if not more.

![15891_SMC-2584ne-14274 vgst_source_den_map_plot](https://user-images.githubusercontent.com/24800168/139324374-0a51de3c-304a-4055-805e-ccd4d1e92ece.png)
![15891_SMC-2750ne-8567 vgst_source_den_map_plot](https://user-images.githubusercontent.com/24800168/139324441-2a415d5c-9ad1-4c26-b187-612f0c26e728.png)

**Comment by christinawlindberg** [comment]
For the first field above (15891_SMC-2584ne-14274), all high-SD regions disappear once I set the frac_area to a minimum of 24%.
Meanwhile, the second field (15891_SMC-2750ne-8567) only needed a frac_area minimum of 12% to eliminate the singular high-SD tile.
So I guess the annoying answer to your question is: it depends 😄 

![15891_SMC-2584ne-14274 vgst_source_den_map_plot](https://user-images.githubusercontent.com/24800168/139951757-d27c0d42-0da8-40dc-a1d3-70520576e019.png)

![15891_SMC-2750ne-8567 vgst_source_den_map_plot](https://user-images.githubusercontent.com/24800168/139951708-d9a11354-0ad0-4c37-92bf-4ed859c9f52a.png)

**Comment by karllark** [comment]
Given this, I would advocate setting this value to 30% or 50% or something like this.  All we will lose are a few spatial pixels at the edge of the field, right?  Better to remove a few extra spatial pixels than to keep troublesome ones.  At least that would be the conservative approach to focus our work on the spatial regions that are fully covered.
