### ISSUE TITLE
Filter bandpasses need updating

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#755]
Work by @galaxyumi revealed that the latest bandpasses downloaded from STScI (https://www.stsci.edu/hst/instrumentation/wfc3/performance/throughputs) were different than the bandpasses in the BEAST filter library.  The differences were especially large for the medium band WFC3 filters.  The BEAST filter library ingested bandpasses downloaded from an STScI web page that had a huge listing of fits files including multiple versions and this page is not currently able to be found.

Interacting with the WFC3 team, it was clear that the best way to get full end-to-end throughput bandpasses is by using the stsynphot python package.

See https://github.com/karllark/beast-books/blob/check_filters/misc/BEAST%20versus%20STSYNPHOT%20Bandpass%20check.ipynb for a comparison of the BEAST and stsynphot bandpasses for many of the filters often used in the BEAST.

Need to use stsynphot and update all the HST bandpass functions in the BEAST filter library.  For instruments with multiple chips (e.g., ACS, WFC3 UVIS) we should average the bandpasses over the chips.  The code to do this updating should be included in the repository and docs written on how to do this.  In addition, possibly setup tests to alert us when/if the bandpass functions change in the future (this could be challenging as stsynphot requires the download of a database).

List of filters in the BEAST: https://beast.readthedocs.io/en/latest/beast_setup.html#beast-filters
We may want to consider removing filters that we cannot document the origin of the bandpass functions.  Especially if we are not using them.

**Comment by cmurray-astro** [comment]
Adding to this, we need to include documentation explaining the new process of how the filter library is created, and how to add new filters.

**Comment by mfouesneau** [comment]
The WFC3 passbands were from ST calspec data in ~2012. I suppose they updated these but I'm surprised these are so different.
 
How do these compare with the SVO service? http://svo2.cab.inta-csic.es/theory/fps/index.php?mode=browse&gname=HST&asttype= 

if you outsource the passband interface you could also solve #759.

**Comment by karllark** [comment]
> The WFC3 passbands were from ST calspec data in ~2012. I suppose they updated these but I'm surprised these are so different.

The issue is that we seem to have only loaded the filter response function *only*.  This did not include there rest of the optical system, especially the responsivity of the detector that significantly cuts off some of the filter leaks.  This is especially important for the medium band WFC3 IR filters, but not the big leaks for the UV filters.

**Comment by karllark** [comment]
> How do these compare with the SVO service? http://svo2.cab.inta-csic.es/theory/fps/index.php?mode=browse&gname=HST&asttype=

Not always up-to-date.  At least for WFC3 according to a WFC3 instrument scientist at STScI.  They have contact the SVO people to hopefully get them up-to-date.

So, the best solution is to get the bandpass response functions from the source used by the instrument scientists at STScI - stsynphot.  And then put them in the BEAST filter library and stsynphot requires a large library of data to work.

**Comment by karllark** [comment]
Done in PR #757.
