### ISSUE TITLE
MIST models with rotation="vvcrit0.4" seem to grab models with rotation="vvcrit0.0"

### ISSUE THREAD

**Issue by galaxyumi** [BEAST-Fitting/beast#763]
@dweisz's student Maude Gull at Berkeley has been exploring the BEAST fits for young massive stars in Leo-A. She tried MIST models with different rotations and noted that those two models return the exactly same parameters for stars. From quick review of isochrone.py code, it seems like ‘rotation’ setting in the beast_settings.txt is not properly reflected when downloading the MIST models. It seems like the BEAST uses "vvcrit0.0” even if you set rotation to “vvcrit0.4” in the settings tile.

**Comment by galaxyumi** [comment]
@lcjohnso Can you take a look at this?

**Comment by maudegull** [comment]
Fix is to put the rotation parameter within MISTWeb()!
oiso = isochrone.MISTWeb(rotation='vvcrit0.4')

**Comment by galaxyumi** [comment]
Then I think we can close this issue! Thanks @maudegull
