### ISSUE TITLE
Why is add_spectral_properties called in creating the spectral grid?

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#764]
The function `add_spectral_properties` is called when generating the spectral grid and then again when generating the SED grid.  Why is this?  The add_spectral_properties function adds fluxes in filters to the grid.  The spectral grid is the full wavelength resolution spectra for all the unextinguished stars.  The SED grid is the fluxes in the desired filters in the grid for the full grid including all the extinguished points.  This seems to be a duplication of effort for the unextinguished points.

This was discovered with the update of the filter bandpasses (PR #757) where `test_make_kurucz_tlusty_spectral_grid` failed.   I had not expected this failure.

**Comment by galaxyumi** [comment]
I seems like the unextinguished flux in each filter is reported in the spectral grid with '_nd' name format when generating the spec grid and then the extinguished flux in each filter is calculated when generating the SED grid and reported with '_wd' name format. So I don't think the actual calculation is repeated. By doing in the current way, the number of calculation for measuring the unextinguished flux in each filter is in fact less than that would be done in the generating the SED grid step. So, I would say this is not a bug.

**Comment by karllark** [comment]
Ah, yes.  That makes sense.  I even have a memory that I may have been the one to add this code.  Hah.
