### ISSUE TITLE
Web location for library files

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#78]
Need a place to provide library files for download.
Could also be used for other binary files (e.g., images, etc for docs).

**Comment by karllark** [comment]
It would be great to have a place to put jupyter notebooks as well.  I just made one with some diagnostic plots.  Probably not the best idea to have lots of such notebooks in the BEAST repository itself (they will start to get big).
Would the github pages be part of this the BEAST repository?  Or a separate one?  Or not a repository at all?

**Comment by mfouesneau** [comment]
notebooks could be in the repo. I think that's a good place if not the proper choice. Github can render them, and there is the online viewer as well to link to other websites

**Comment by karllark** [comment]
My concern with having the notebooks as part of the repository is that they are not necessarily small.   I have one with 6ish plots in it and it is 0.5 Mbyte.  If we add many notebooks, we will quickly make the repository large (again).  
In addition, the number of lines in a notebook is large and causes the BEAST repository to be tagged as a Jupyter notebook not a python project.

**Comment by meredith-durbin** [comment]
Another repo (something like `beast-notebooks`) sounds like a good solution to me, especially once the BEAST is installable and can be run from any directory.

**Comment by karllark** [comment]
For now, I've put the libraries at:
https://stsci.box.com/v/beastlibs

**Comment by karllark** [comment]
Would be good if there was a way to have these distributed with the beast code.  There is something as part of the astropy affiliated template about 'remote-data' that might work.  I haven't investigated in detail yet.  This is something that can be use for the testing code at least - which would be needed for any full run tests of the beast.

**Comment by karllark** [comment]
Subsumed by #155.
