### ISSUE TITLE
Filters missing from newest vega.hd5 and filters.hd5 library files

### ISSUE THREAD

**Issue by petiay** [BEAST-Fitting/beast#786]
This issue is related to the discussion in #755, [PR#757](https://github.com/BEAST-Fitting/beast/pull/757), #759, and #778.

The newest version of the [BEAST library files](https://beast.readthedocs.io/en/latest/install.html) available either via manual download (Oct 2022) or via `beast get_libfiles` does not seem to contain all the filters in the version of the library files from March 2022.
For example, HST_ACS_WFC_F658N is missing. Generally there are 61 vs 189 filters available in the Oct vs the Mar 2022 files. I can not find a particular discussion to trim the list, so perhaps we just need to update the new list to make sure it includes all filters we need. @cmurray-astro , @galaxyumi , @karllark , comments are welcome.

I see some discussion in [PR#757](https://github.com/BEAST-Fitting/beast/pull/757), but since a version of the library files from just after the discussion (Mar'22) includes the larger filter list, but the new version from Oct'22 is trimmed, then I am a bit confused.

**Comment by karllark** [comment]
Narrow band filters adding in PR #799.  This PR will close this issue.  A new issues should be opened requested specific filters.
