### ISSUE TITLE
Update for python 3 

### ISSUE THREAD

**Issue by karllark** [BEAST-Fitting/beast#8]
The beast works with python 2.7, but not python 3 or greater.
Update needed mainly to handle the print statements.  Use 'from future import print, division' at a minimum.

**Comment by karllark** [comment]
@rubab1 Are you still interested in leading the work on this issue?

**Comment by rubab1** [comment]
@karllark Yes, but will have very limited time for this. If this is time sensitive on months (or shorter) scale, I'd not be the best one to do this. ... What do you think?

**Comment by karllark** [comment]
@rubab1 Maybe not you then.  I'll leave make this unassigned and then anyone who wants too can do it.

**Comment by rubab1** [comment]
@karllark Cool 👍

**Comment by karllark** [comment]
I am working on this.   I have made good progress during the M31 Lorentz meeting.  Lots of files are modified - fair warning!
