### ISSUE TITLE
Replace pkg_resources: deprecated

### ISSUE THREAD

**Issue by petiay** [BEAST-Fitting/beast#804]
pkg_resources seems to be used in three places. But it "is deprecated in favor of importlib.resources, importlib.metadata and their backports (importlib_resources, importlib_metadata)": https://setuptools.pypa.io/en/latest/pkg_resources.html

**Comment by karllark** [comment]
I've heard this one a discussion of another package.   Sounds like a straightforward fix.  Maybe at the next BEAST HackDay!

**Comment by petiay** [comment]
Yes, it does look straightforward. At the next Hack day!
