### ISSUE TITLE
tables package cannot be installed using pip (not built on pypi?), but can be installed via conda

### ISSUE THREAD

**Issue by Stargrazer82301** [BEAST-Fitting/beast#811]
As in title. When trying to install the BEAST as per standard install instructions, via `pip install beast`, it crashes because pip cannot install the `tables` package. However, if one installs table via c`onda install tables` first, then tries to install the BEAST, it goes through.

May have to update install instructions? But awkward to have to install a single package first via a different install method...

**Comment by karllark** [comment]
I have been able to get the tables package to install via pip.  Maybe this has been fixed?

**Comment by Stargrazer82301** [comment]
Yep, also seems to work for me now. Guess it was a temporary issue with the
pypi build, now fixed?
